// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module StreamingDataflowPartition_2_IODMA_0_Stream2Mem_Batch (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        in_V_V_TDATA,
        in_V_V_TVALID,
        in_V_V_TREADY,
        m_axi_out_V_AWVALID,
        m_axi_out_V_AWREADY,
        m_axi_out_V_AWADDR,
        m_axi_out_V_AWID,
        m_axi_out_V_AWLEN,
        m_axi_out_V_AWSIZE,
        m_axi_out_V_AWBURST,
        m_axi_out_V_AWLOCK,
        m_axi_out_V_AWCACHE,
        m_axi_out_V_AWPROT,
        m_axi_out_V_AWQOS,
        m_axi_out_V_AWREGION,
        m_axi_out_V_AWUSER,
        m_axi_out_V_WVALID,
        m_axi_out_V_WREADY,
        m_axi_out_V_WDATA,
        m_axi_out_V_WSTRB,
        m_axi_out_V_WLAST,
        m_axi_out_V_WID,
        m_axi_out_V_WUSER,
        m_axi_out_V_ARVALID,
        m_axi_out_V_ARREADY,
        m_axi_out_V_ARADDR,
        m_axi_out_V_ARID,
        m_axi_out_V_ARLEN,
        m_axi_out_V_ARSIZE,
        m_axi_out_V_ARBURST,
        m_axi_out_V_ARLOCK,
        m_axi_out_V_ARCACHE,
        m_axi_out_V_ARPROT,
        m_axi_out_V_ARQOS,
        m_axi_out_V_ARREGION,
        m_axi_out_V_ARUSER,
        m_axi_out_V_RVALID,
        m_axi_out_V_RREADY,
        m_axi_out_V_RDATA,
        m_axi_out_V_RLAST,
        m_axi_out_V_RID,
        m_axi_out_V_RUSER,
        m_axi_out_V_RRESP,
        m_axi_out_V_BVALID,
        m_axi_out_V_BREADY,
        m_axi_out_V_BRESP,
        m_axi_out_V_BID,
        m_axi_out_V_BUSER,
        out_V_offset,
        numReps
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] in_V_V_TDATA;
input   in_V_V_TVALID;
output   in_V_V_TREADY;
output   m_axi_out_V_AWVALID;
input   m_axi_out_V_AWREADY;
output  [63:0] m_axi_out_V_AWADDR;
output  [0:0] m_axi_out_V_AWID;
output  [31:0] m_axi_out_V_AWLEN;
output  [2:0] m_axi_out_V_AWSIZE;
output  [1:0] m_axi_out_V_AWBURST;
output  [1:0] m_axi_out_V_AWLOCK;
output  [3:0] m_axi_out_V_AWCACHE;
output  [2:0] m_axi_out_V_AWPROT;
output  [3:0] m_axi_out_V_AWQOS;
output  [3:0] m_axi_out_V_AWREGION;
output  [0:0] m_axi_out_V_AWUSER;
output   m_axi_out_V_WVALID;
input   m_axi_out_V_WREADY;
output  [7:0] m_axi_out_V_WDATA;
output  [0:0] m_axi_out_V_WSTRB;
output   m_axi_out_V_WLAST;
output  [0:0] m_axi_out_V_WID;
output  [0:0] m_axi_out_V_WUSER;
output   m_axi_out_V_ARVALID;
input   m_axi_out_V_ARREADY;
output  [63:0] m_axi_out_V_ARADDR;
output  [0:0] m_axi_out_V_ARID;
output  [31:0] m_axi_out_V_ARLEN;
output  [2:0] m_axi_out_V_ARSIZE;
output  [1:0] m_axi_out_V_ARBURST;
output  [1:0] m_axi_out_V_ARLOCK;
output  [3:0] m_axi_out_V_ARCACHE;
output  [2:0] m_axi_out_V_ARPROT;
output  [3:0] m_axi_out_V_ARQOS;
output  [3:0] m_axi_out_V_ARREGION;
output  [0:0] m_axi_out_V_ARUSER;
input   m_axi_out_V_RVALID;
output   m_axi_out_V_RREADY;
input  [7:0] m_axi_out_V_RDATA;
input   m_axi_out_V_RLAST;
input  [0:0] m_axi_out_V_RID;
input  [0:0] m_axi_out_V_RUSER;
input  [1:0] m_axi_out_V_RRESP;
input   m_axi_out_V_BVALID;
output   m_axi_out_V_BREADY;
input  [1:0] m_axi_out_V_BRESP;
input  [0:0] m_axi_out_V_BID;
input  [0:0] m_axi_out_V_BUSER;
input  [63:0] out_V_offset;
input  [31:0] numReps;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_V_V_TREADY;
reg m_axi_out_V_AWVALID;
reg[63:0] m_axi_out_V_AWADDR;
reg[0:0] m_axi_out_V_AWID;
reg[31:0] m_axi_out_V_AWLEN;
reg[2:0] m_axi_out_V_AWSIZE;
reg[1:0] m_axi_out_V_AWBURST;
reg[1:0] m_axi_out_V_AWLOCK;
reg[3:0] m_axi_out_V_AWCACHE;
reg[2:0] m_axi_out_V_AWPROT;
reg[3:0] m_axi_out_V_AWQOS;
reg[3:0] m_axi_out_V_AWREGION;
reg[0:0] m_axi_out_V_AWUSER;
reg m_axi_out_V_WVALID;
reg[7:0] m_axi_out_V_WDATA;
reg[0:0] m_axi_out_V_WSTRB;
reg m_axi_out_V_WLAST;
reg[0:0] m_axi_out_V_WID;
reg[0:0] m_axi_out_V_WUSER;
reg m_axi_out_V_BREADY;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_Stream2Mem_8u_1u_s_fu_64_in_V_V_TDATA_blk_n;
reg    in_V_V_TDATA_blk_n;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state10;
reg   [0:0] icmp_ln189_reg_154;
wire    grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_AW;
wire    grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_W;
wire    grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_B;
reg    out_V_blk_n_AW;
reg    out_V_blk_n_W;
reg    out_V_blk_n_B;
reg    ap_block_state1;
reg   [31:0] rep_2_load_reg_143;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln189_fu_97_p2;
wire   [0:0] icmp_ln187_fu_83_p2;
wire    grp_Stream2Mem_8u_16u_s_fu_54_ap_start;
wire    grp_Stream2Mem_8u_16u_s_fu_54_ap_done;
wire    grp_Stream2Mem_8u_16u_s_fu_54_ap_idle;
wire    grp_Stream2Mem_8u_16u_s_fu_54_ap_ready;
wire    grp_Stream2Mem_8u_16u_s_fu_54_in_V_V_TREADY;
wire    grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWVALID;
wire   [63:0] grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWADDR;
wire   [0:0] grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWID;
wire   [31:0] grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWLEN;
wire   [2:0] grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWSIZE;
wire   [1:0] grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWBURST;
wire   [1:0] grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWLOCK;
wire   [3:0] grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWCACHE;
wire   [2:0] grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWPROT;
wire   [3:0] grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWQOS;
wire   [3:0] grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWREGION;
wire   [0:0] grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWUSER;
wire    grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_WVALID;
wire   [7:0] grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_WDATA;
wire   [0:0] grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_WSTRB;
wire    grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_WLAST;
wire   [0:0] grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_WID;
wire   [0:0] grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_WUSER;
wire    grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_ARVALID;
wire   [63:0] grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_ARADDR;
wire   [0:0] grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_ARID;
wire   [31:0] grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_ARLEN;
wire   [2:0] grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_ARSIZE;
wire   [1:0] grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_ARBURST;
wire   [1:0] grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_ARLOCK;
wire   [3:0] grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_ARCACHE;
wire   [2:0] grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_ARPROT;
wire   [3:0] grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_ARQOS;
wire   [3:0] grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_ARREGION;
wire   [0:0] grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_ARUSER;
wire    grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_RREADY;
wire    grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_BREADY;
wire    grp_Stream2Mem_8u_1u_s_fu_64_ap_start;
wire    grp_Stream2Mem_8u_1u_s_fu_64_ap_done;
wire    grp_Stream2Mem_8u_1u_s_fu_64_ap_idle;
wire    grp_Stream2Mem_8u_1u_s_fu_64_ap_ready;
wire    grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWVALID;
wire   [63:0] grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWADDR;
wire   [0:0] grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWID;
wire   [31:0] grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWLEN;
wire   [2:0] grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWSIZE;
wire   [1:0] grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWBURST;
wire   [1:0] grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWLOCK;
wire   [3:0] grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWCACHE;
wire   [2:0] grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWPROT;
wire   [3:0] grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWQOS;
wire   [3:0] grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWREGION;
wire   [0:0] grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWUSER;
wire    grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_WVALID;
wire   [7:0] grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_WDATA;
wire   [0:0] grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_WSTRB;
wire    grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_WLAST;
wire   [0:0] grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_WID;
wire   [0:0] grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_WUSER;
wire    grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_ARVALID;
wire   [63:0] grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_ARADDR;
wire   [0:0] grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_ARID;
wire   [31:0] grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_ARLEN;
wire   [2:0] grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_ARSIZE;
wire   [1:0] grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_ARBURST;
wire   [1:0] grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_ARLOCK;
wire   [3:0] grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_ARCACHE;
wire   [2:0] grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_ARPROT;
wire   [3:0] grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_ARQOS;
wire   [3:0] grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_ARREGION;
wire   [0:0] grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_ARUSER;
wire    grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_RREADY;
wire    grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_BREADY;
wire    grp_Stream2Mem_8u_1u_s_fu_64_in_V_V_TREADY;
reg    grp_Stream2Mem_8u_16u_s_fu_54_ap_start_reg;
wire    ap_CS_fsm_state11;
reg    grp_Stream2Mem_8u_1u_s_fu_64_ap_start_reg;
reg   [10:0] ap_NS_fsm;
wire    ap_NS_fsm_state3;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg   [31:0] rep_2_fu_38;
wire   [31:0] rep_3_fu_103_p2;
reg    ap_block_state3;
wire   [31:0] rep_fu_113_p2;
wire   [31:0] repsLeft_fu_88_p2;
wire   [3:0] trunc_ln188_fu_93_p1;
reg    ap_block_state4;
reg    ap_block_state5;
reg    ap_block_state10;
wire    regslice_both_in_V_V_U_apdone_blk;
wire   [7:0] in_V_V_TDATA_int;
wire    in_V_V_TVALID_int;
reg    in_V_V_TREADY_int;
wire    regslice_both_in_V_V_U_ack_in;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 11'd1;
#0 grp_Stream2Mem_8u_16u_s_fu_54_ap_start_reg = 1'b0;
#0 grp_Stream2Mem_8u_1u_s_fu_64_ap_start_reg = 1'b0;
end

StreamingDataflowPartition_2_IODMA_0_Stream2Mem_8u_16u_s grp_Stream2Mem_8u_16u_s_fu_54(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Stream2Mem_8u_16u_s_fu_54_ap_start),
    .ap_done(grp_Stream2Mem_8u_16u_s_fu_54_ap_done),
    .ap_idle(grp_Stream2Mem_8u_16u_s_fu_54_ap_idle),
    .ap_ready(grp_Stream2Mem_8u_16u_s_fu_54_ap_ready),
    .in_V_V_TDATA(in_V_V_TDATA_int),
    .in_V_V_TVALID(in_V_V_TVALID_int),
    .in_V_V_TREADY(grp_Stream2Mem_8u_16u_s_fu_54_in_V_V_TREADY),
    .m_axi_out_V_AWVALID(grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWVALID),
    .m_axi_out_V_AWREADY(m_axi_out_V_AWREADY),
    .m_axi_out_V_AWADDR(grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWADDR),
    .m_axi_out_V_AWID(grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWID),
    .m_axi_out_V_AWLEN(grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWLEN),
    .m_axi_out_V_AWSIZE(grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWSIZE),
    .m_axi_out_V_AWBURST(grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWBURST),
    .m_axi_out_V_AWLOCK(grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWLOCK),
    .m_axi_out_V_AWCACHE(grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWCACHE),
    .m_axi_out_V_AWPROT(grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWPROT),
    .m_axi_out_V_AWQOS(grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWQOS),
    .m_axi_out_V_AWREGION(grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWREGION),
    .m_axi_out_V_AWUSER(grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWUSER),
    .m_axi_out_V_WVALID(grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_WVALID),
    .m_axi_out_V_WREADY(m_axi_out_V_WREADY),
    .m_axi_out_V_WDATA(grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_WDATA),
    .m_axi_out_V_WSTRB(grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_WSTRB),
    .m_axi_out_V_WLAST(grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_WLAST),
    .m_axi_out_V_WID(grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_WID),
    .m_axi_out_V_WUSER(grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_WUSER),
    .m_axi_out_V_ARVALID(grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_ARVALID),
    .m_axi_out_V_ARREADY(1'b0),
    .m_axi_out_V_ARADDR(grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_ARADDR),
    .m_axi_out_V_ARID(grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_ARID),
    .m_axi_out_V_ARLEN(grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_ARLEN),
    .m_axi_out_V_ARSIZE(grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_ARSIZE),
    .m_axi_out_V_ARBURST(grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_ARBURST),
    .m_axi_out_V_ARLOCK(grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_ARLOCK),
    .m_axi_out_V_ARCACHE(grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_ARCACHE),
    .m_axi_out_V_ARPROT(grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_ARPROT),
    .m_axi_out_V_ARQOS(grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_ARQOS),
    .m_axi_out_V_ARREGION(grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_ARREGION),
    .m_axi_out_V_ARUSER(grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_ARUSER),
    .m_axi_out_V_RVALID(1'b0),
    .m_axi_out_V_RREADY(grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_RREADY),
    .m_axi_out_V_RDATA(8'd0),
    .m_axi_out_V_RLAST(1'b0),
    .m_axi_out_V_RID(1'd0),
    .m_axi_out_V_RUSER(1'd0),
    .m_axi_out_V_RRESP(2'd0),
    .m_axi_out_V_BVALID(m_axi_out_V_BVALID),
    .m_axi_out_V_BREADY(grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_BREADY),
    .m_axi_out_V_BRESP(m_axi_out_V_BRESP),
    .m_axi_out_V_BID(m_axi_out_V_BID),
    .m_axi_out_V_BUSER(m_axi_out_V_BUSER),
    .out_V_offset(out_V_offset),
    .out_V_offset1(rep_2_load_reg_143)
);

StreamingDataflowPartition_2_IODMA_0_Stream2Mem_8u_1u_s grp_Stream2Mem_8u_1u_s_fu_64(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Stream2Mem_8u_1u_s_fu_64_ap_start),
    .ap_done(grp_Stream2Mem_8u_1u_s_fu_64_ap_done),
    .ap_idle(grp_Stream2Mem_8u_1u_s_fu_64_ap_idle),
    .ap_ready(grp_Stream2Mem_8u_1u_s_fu_64_ap_ready),
    .in_V_V_TVALID(in_V_V_TVALID_int),
    .m_axi_out_V_AWVALID(grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWVALID),
    .m_axi_out_V_AWREADY(m_axi_out_V_AWREADY),
    .m_axi_out_V_AWADDR(grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWADDR),
    .m_axi_out_V_AWID(grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWID),
    .m_axi_out_V_AWLEN(grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWLEN),
    .m_axi_out_V_AWSIZE(grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWSIZE),
    .m_axi_out_V_AWBURST(grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWBURST),
    .m_axi_out_V_AWLOCK(grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWLOCK),
    .m_axi_out_V_AWCACHE(grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWCACHE),
    .m_axi_out_V_AWPROT(grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWPROT),
    .m_axi_out_V_AWQOS(grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWQOS),
    .m_axi_out_V_AWREGION(grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWREGION),
    .m_axi_out_V_AWUSER(grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWUSER),
    .m_axi_out_V_WVALID(grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_WVALID),
    .m_axi_out_V_WREADY(m_axi_out_V_WREADY),
    .m_axi_out_V_WDATA(grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_WDATA),
    .m_axi_out_V_WSTRB(grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_WSTRB),
    .m_axi_out_V_WLAST(grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_WLAST),
    .m_axi_out_V_WID(grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_WID),
    .m_axi_out_V_WUSER(grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_WUSER),
    .m_axi_out_V_ARVALID(grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_ARVALID),
    .m_axi_out_V_ARREADY(1'b0),
    .m_axi_out_V_ARADDR(grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_ARADDR),
    .m_axi_out_V_ARID(grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_ARID),
    .m_axi_out_V_ARLEN(grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_ARLEN),
    .m_axi_out_V_ARSIZE(grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_ARSIZE),
    .m_axi_out_V_ARBURST(grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_ARBURST),
    .m_axi_out_V_ARLOCK(grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_ARLOCK),
    .m_axi_out_V_ARCACHE(grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_ARCACHE),
    .m_axi_out_V_ARPROT(grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_ARPROT),
    .m_axi_out_V_ARQOS(grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_ARQOS),
    .m_axi_out_V_ARREGION(grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_ARREGION),
    .m_axi_out_V_ARUSER(grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_ARUSER),
    .m_axi_out_V_RVALID(1'b0),
    .m_axi_out_V_RREADY(grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_RREADY),
    .m_axi_out_V_RDATA(8'd0),
    .m_axi_out_V_RLAST(1'b0),
    .m_axi_out_V_RID(1'd0),
    .m_axi_out_V_RUSER(1'd0),
    .m_axi_out_V_RRESP(2'd0),
    .m_axi_out_V_BVALID(m_axi_out_V_BVALID),
    .m_axi_out_V_BREADY(grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_BREADY),
    .m_axi_out_V_BRESP(m_axi_out_V_BRESP),
    .m_axi_out_V_BID(m_axi_out_V_BID),
    .m_axi_out_V_BUSER(m_axi_out_V_BUSER),
    .in_V_V_TDATA(in_V_V_TDATA_int),
    .in_V_V_TREADY(grp_Stream2Mem_8u_1u_s_fu_64_in_V_V_TREADY),
    .out_V_offset(out_V_offset),
    .out_V_offset1(rep_2_load_reg_143),
    .in_V_V_TDATA_blk_n(grp_Stream2Mem_8u_1u_s_fu_64_in_V_V_TDATA_blk_n),
    .out_V_blk_n_AW(grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_AW),
    .out_V_blk_n_W(grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_W),
    .out_V_blk_n_B(grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_B)
);

regslice_both #(
    .DataWidth( 8 ))
regslice_both_in_V_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(in_V_V_TDATA),
    .vld_in(in_V_V_TVALID),
    .ack_in(regslice_both_in_V_V_U_ack_in),
    .data_out(in_V_V_TDATA_int),
    .vld_out(in_V_V_TVALID_int),
    .ack_out(in_V_V_TREADY_int),
    .apdone_blk(regslice_both_in_V_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln187_fu_83_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Stream2Mem_8u_16u_s_fu_54_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln187_fu_83_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln189_fu_97_p2 == 1'd1))) begin
            grp_Stream2Mem_8u_16u_s_fu_54_ap_start_reg <= 1'b1;
        end else if ((grp_Stream2Mem_8u_16u_s_fu_54_ap_ready == 1'b1)) begin
            grp_Stream2Mem_8u_16u_s_fu_54_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Stream2Mem_8u_1u_s_fu_64_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state3) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_Stream2Mem_8u_1u_s_fu_64_ap_start_reg <= 1'b1;
        end else if ((grp_Stream2Mem_8u_1u_s_fu_64_ap_ready == 1'b1)) begin
            grp_Stream2Mem_8u_1u_s_fu_64_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & (grp_Stream2Mem_8u_16u_s_fu_54_ap_done == 1'b1))) begin
        rep_2_fu_38 <= rep_fu_113_p2;
    end else if ((~((grp_Stream2Mem_8u_1u_s_fu_64_in_V_V_TDATA_blk_n == 1'b0) | ((grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_W & grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_B & grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_AW) == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
        rep_2_fu_38 <= rep_3_fu_103_p2;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        rep_2_fu_38 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln187_fu_83_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        icmp_ln189_reg_154 <= icmp_ln189_fu_97_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        rep_2_load_reg_143 <= rep_2_fu_38;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln187_fu_83_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln187_fu_83_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((icmp_ln189_reg_154 == 1'd0) & (1'b1 == ap_CS_fsm_state10)))) begin
        in_V_V_TDATA_blk_n = grp_Stream2Mem_8u_1u_s_fu_64_in_V_V_TDATA_blk_n;
    end else begin
        in_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((regslice_both_in_V_V_U_ack_in == 1'b1) & (in_V_V_TVALID == 1'b1))) begin
        in_V_V_TREADY = 1'b1;
    end else begin
        in_V_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_V_V_TREADY_int = grp_Stream2Mem_8u_1u_s_fu_64_in_V_V_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        in_V_V_TREADY_int = grp_Stream2Mem_8u_16u_s_fu_54_in_V_V_TREADY;
    end else begin
        in_V_V_TREADY_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((icmp_ln189_reg_154 == 1'd0) & (1'b1 == ap_CS_fsm_state10)))) begin
        m_axi_out_V_AWADDR = grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWADDR;
    end else if (((1'b1 == ap_CS_fsm_state11) | ((icmp_ln187_fu_83_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln189_fu_97_p2 == 1'd1)))) begin
        m_axi_out_V_AWADDR = grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWADDR;
    end else begin
        m_axi_out_V_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((icmp_ln189_reg_154 == 1'd0) & (1'b1 == ap_CS_fsm_state10)))) begin
        m_axi_out_V_AWBURST = grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWBURST;
    end else if (((1'b1 == ap_CS_fsm_state11) | ((icmp_ln187_fu_83_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln189_fu_97_p2 == 1'd1)))) begin
        m_axi_out_V_AWBURST = grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWBURST;
    end else begin
        m_axi_out_V_AWBURST = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((icmp_ln189_reg_154 == 1'd0) & (1'b1 == ap_CS_fsm_state10)))) begin
        m_axi_out_V_AWCACHE = grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWCACHE;
    end else if (((1'b1 == ap_CS_fsm_state11) | ((icmp_ln187_fu_83_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln189_fu_97_p2 == 1'd1)))) begin
        m_axi_out_V_AWCACHE = grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWCACHE;
    end else begin
        m_axi_out_V_AWCACHE = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((icmp_ln189_reg_154 == 1'd0) & (1'b1 == ap_CS_fsm_state10)))) begin
        m_axi_out_V_AWID = grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWID;
    end else if (((1'b1 == ap_CS_fsm_state11) | ((icmp_ln187_fu_83_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln189_fu_97_p2 == 1'd1)))) begin
        m_axi_out_V_AWID = grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWID;
    end else begin
        m_axi_out_V_AWID = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((icmp_ln189_reg_154 == 1'd0) & (1'b1 == ap_CS_fsm_state10)))) begin
        m_axi_out_V_AWLEN = grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWLEN;
    end else if (((1'b1 == ap_CS_fsm_state11) | ((icmp_ln187_fu_83_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln189_fu_97_p2 == 1'd1)))) begin
        m_axi_out_V_AWLEN = grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWLEN;
    end else begin
        m_axi_out_V_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((icmp_ln189_reg_154 == 1'd0) & (1'b1 == ap_CS_fsm_state10)))) begin
        m_axi_out_V_AWLOCK = grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWLOCK;
    end else if (((1'b1 == ap_CS_fsm_state11) | ((icmp_ln187_fu_83_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln189_fu_97_p2 == 1'd1)))) begin
        m_axi_out_V_AWLOCK = grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWLOCK;
    end else begin
        m_axi_out_V_AWLOCK = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((icmp_ln189_reg_154 == 1'd0) & (1'b1 == ap_CS_fsm_state10)))) begin
        m_axi_out_V_AWPROT = grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWPROT;
    end else if (((1'b1 == ap_CS_fsm_state11) | ((icmp_ln187_fu_83_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln189_fu_97_p2 == 1'd1)))) begin
        m_axi_out_V_AWPROT = grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWPROT;
    end else begin
        m_axi_out_V_AWPROT = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((icmp_ln189_reg_154 == 1'd0) & (1'b1 == ap_CS_fsm_state10)))) begin
        m_axi_out_V_AWQOS = grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWQOS;
    end else if (((1'b1 == ap_CS_fsm_state11) | ((icmp_ln187_fu_83_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln189_fu_97_p2 == 1'd1)))) begin
        m_axi_out_V_AWQOS = grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWQOS;
    end else begin
        m_axi_out_V_AWQOS = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((icmp_ln189_reg_154 == 1'd0) & (1'b1 == ap_CS_fsm_state10)))) begin
        m_axi_out_V_AWREGION = grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWREGION;
    end else if (((1'b1 == ap_CS_fsm_state11) | ((icmp_ln187_fu_83_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln189_fu_97_p2 == 1'd1)))) begin
        m_axi_out_V_AWREGION = grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWREGION;
    end else begin
        m_axi_out_V_AWREGION = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((icmp_ln189_reg_154 == 1'd0) & (1'b1 == ap_CS_fsm_state10)))) begin
        m_axi_out_V_AWSIZE = grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWSIZE;
    end else if (((1'b1 == ap_CS_fsm_state11) | ((icmp_ln187_fu_83_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln189_fu_97_p2 == 1'd1)))) begin
        m_axi_out_V_AWSIZE = grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWSIZE;
    end else begin
        m_axi_out_V_AWSIZE = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((icmp_ln189_reg_154 == 1'd0) & (1'b1 == ap_CS_fsm_state10)))) begin
        m_axi_out_V_AWUSER = grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWUSER;
    end else if (((1'b1 == ap_CS_fsm_state11) | ((icmp_ln187_fu_83_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln189_fu_97_p2 == 1'd1)))) begin
        m_axi_out_V_AWUSER = grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWUSER;
    end else begin
        m_axi_out_V_AWUSER = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((icmp_ln189_reg_154 == 1'd0) & (1'b1 == ap_CS_fsm_state10)))) begin
        m_axi_out_V_AWVALID = grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_AWVALID;
    end else if (((1'b1 == ap_CS_fsm_state11) | ((icmp_ln187_fu_83_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln189_fu_97_p2 == 1'd1)))) begin
        m_axi_out_V_AWVALID = grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_AWVALID;
    end else begin
        m_axi_out_V_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((icmp_ln189_reg_154 == 1'd0) & (1'b1 == ap_CS_fsm_state10)))) begin
        m_axi_out_V_BREADY = grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_BREADY;
    end else if (((1'b1 == ap_CS_fsm_state11) | ((icmp_ln187_fu_83_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln189_fu_97_p2 == 1'd1)))) begin
        m_axi_out_V_BREADY = grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_BREADY;
    end else begin
        m_axi_out_V_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((icmp_ln189_reg_154 == 1'd0) & (1'b1 == ap_CS_fsm_state10)))) begin
        m_axi_out_V_WDATA = grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_WDATA;
    end else if (((1'b1 == ap_CS_fsm_state11) | ((icmp_ln187_fu_83_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln189_fu_97_p2 == 1'd1)))) begin
        m_axi_out_V_WDATA = grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_WDATA;
    end else begin
        m_axi_out_V_WDATA = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((icmp_ln189_reg_154 == 1'd0) & (1'b1 == ap_CS_fsm_state10)))) begin
        m_axi_out_V_WID = grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_WID;
    end else if (((1'b1 == ap_CS_fsm_state11) | ((icmp_ln187_fu_83_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln189_fu_97_p2 == 1'd1)))) begin
        m_axi_out_V_WID = grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_WID;
    end else begin
        m_axi_out_V_WID = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((icmp_ln189_reg_154 == 1'd0) & (1'b1 == ap_CS_fsm_state10)))) begin
        m_axi_out_V_WLAST = grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_WLAST;
    end else if (((1'b1 == ap_CS_fsm_state11) | ((icmp_ln187_fu_83_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln189_fu_97_p2 == 1'd1)))) begin
        m_axi_out_V_WLAST = grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_WLAST;
    end else begin
        m_axi_out_V_WLAST = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((icmp_ln189_reg_154 == 1'd0) & (1'b1 == ap_CS_fsm_state10)))) begin
        m_axi_out_V_WSTRB = grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_WSTRB;
    end else if (((1'b1 == ap_CS_fsm_state11) | ((icmp_ln187_fu_83_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln189_fu_97_p2 == 1'd1)))) begin
        m_axi_out_V_WSTRB = grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_WSTRB;
    end else begin
        m_axi_out_V_WSTRB = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((icmp_ln189_reg_154 == 1'd0) & (1'b1 == ap_CS_fsm_state10)))) begin
        m_axi_out_V_WUSER = grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_WUSER;
    end else if (((1'b1 == ap_CS_fsm_state11) | ((icmp_ln187_fu_83_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln189_fu_97_p2 == 1'd1)))) begin
        m_axi_out_V_WUSER = grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_WUSER;
    end else begin
        m_axi_out_V_WUSER = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((icmp_ln189_reg_154 == 1'd0) & (1'b1 == ap_CS_fsm_state10)))) begin
        m_axi_out_V_WVALID = grp_Stream2Mem_8u_1u_s_fu_64_m_axi_out_V_WVALID;
    end else if (((1'b1 == ap_CS_fsm_state11) | ((icmp_ln187_fu_83_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln189_fu_97_p2 == 1'd1)))) begin
        m_axi_out_V_WVALID = grp_Stream2Mem_8u_16u_s_fu_54_m_axi_out_V_WVALID;
    end else begin
        m_axi_out_V_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((icmp_ln189_reg_154 == 1'd0) & (1'b1 == ap_CS_fsm_state10)))) begin
        out_V_blk_n_AW = grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_AW;
    end else begin
        out_V_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((icmp_ln189_reg_154 == 1'd0) & (1'b1 == ap_CS_fsm_state10)))) begin
        out_V_blk_n_B = grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_B;
    end else begin
        out_V_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((icmp_ln189_reg_154 == 1'd0) & (1'b1 == ap_CS_fsm_state10)))) begin
        out_V_blk_n_W = grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_W;
    end else begin
        out_V_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln187_fu_83_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((icmp_ln187_fu_83_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln189_fu_97_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if ((~((grp_Stream2Mem_8u_1u_s_fu_64_in_V_V_TDATA_blk_n == 1'b0) | ((grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_W & grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_B & grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_AW) == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if ((~((grp_Stream2Mem_8u_1u_s_fu_64_in_V_V_TDATA_blk_n == 1'b0) | ((grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_W & grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_B & grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_AW) == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if ((~((grp_Stream2Mem_8u_1u_s_fu_64_in_V_V_TDATA_blk_n == 1'b0) | ((grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_W & grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_B & grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_AW) == 1'b0)) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if ((~((icmp_ln189_reg_154 == 1'd0) & ((grp_Stream2Mem_8u_1u_s_fu_64_in_V_V_TDATA_blk_n == 1'b0) | ((grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_W & grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_B & grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_AW) == 1'b0))) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_CS_fsm_state11) & (grp_Stream2Mem_8u_16u_s_fu_54_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_NS_fsm_state3 = ap_NS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state10 = ((icmp_ln189_reg_154 == 1'd0) & ((grp_Stream2Mem_8u_1u_s_fu_64_in_V_V_TDATA_blk_n == 1'b0) | ((grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_W & grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_B & grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_AW) == 1'b0)));
end

always @ (*) begin
    ap_block_state3 = ((grp_Stream2Mem_8u_1u_s_fu_64_in_V_V_TDATA_blk_n == 1'b0) | ((grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_W & grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_B & grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_AW) == 1'b0));
end

always @ (*) begin
    ap_block_state4 = ((grp_Stream2Mem_8u_1u_s_fu_64_in_V_V_TDATA_blk_n == 1'b0) | ((grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_W & grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_B & grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_AW) == 1'b0));
end

always @ (*) begin
    ap_block_state5 = ((grp_Stream2Mem_8u_1u_s_fu_64_in_V_V_TDATA_blk_n == 1'b0) | ((grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_W & grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_B & grp_Stream2Mem_8u_1u_s_fu_64_out_V_blk_n_AW) == 1'b0));
end

assign grp_Stream2Mem_8u_16u_s_fu_54_ap_start = grp_Stream2Mem_8u_16u_s_fu_54_ap_start_reg;

assign grp_Stream2Mem_8u_1u_s_fu_64_ap_start = grp_Stream2Mem_8u_1u_s_fu_64_ap_start_reg;

assign icmp_ln187_fu_83_p2 = ((rep_2_fu_38 == numReps) ? 1'b1 : 1'b0);

assign icmp_ln189_fu_97_p2 = ((trunc_ln188_fu_93_p1 == 4'd0) ? 1'b1 : 1'b0);

assign m_axi_out_V_ARADDR = 64'd0;

assign m_axi_out_V_ARBURST = 2'd0;

assign m_axi_out_V_ARCACHE = 4'd0;

assign m_axi_out_V_ARID = 1'd0;

assign m_axi_out_V_ARLEN = 32'd0;

assign m_axi_out_V_ARLOCK = 2'd0;

assign m_axi_out_V_ARPROT = 3'd0;

assign m_axi_out_V_ARQOS = 4'd0;

assign m_axi_out_V_ARREGION = 4'd0;

assign m_axi_out_V_ARSIZE = 3'd0;

assign m_axi_out_V_ARUSER = 1'd0;

assign m_axi_out_V_ARVALID = 1'b0;

assign m_axi_out_V_RREADY = 1'b0;

assign rep_3_fu_103_p2 = (rep_2_load_reg_143 + 32'd1);

assign rep_fu_113_p2 = (rep_2_load_reg_143 + 32'd16);

assign repsLeft_fu_88_p2 = (numReps - rep_2_fu_38);

assign trunc_ln188_fu_93_p1 = repsLeft_fu_88_p2[3:0];

endmodule //StreamingDataflowPartition_2_IODMA_0_Stream2Mem_Batch
