// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module StreamingFCLayer_Batch_1_Matrix_Vector_Activa (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_V_V_TDATA,
        in_V_V_TVALID,
        in_V_V_TREADY,
        out_V_V_TDATA,
        out_V_V_TVALID,
        out_V_V_TREADY,
        weight_V_V_TDATA,
        weight_V_V_TVALID,
        weight_V_V_TREADY
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state5 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] in_V_V_TDATA;
input   in_V_V_TVALID;
output   in_V_V_TREADY;
output  [7:0] out_V_V_TDATA;
output   out_V_V_TVALID;
input   out_V_V_TREADY;
input  [127:0] weight_V_V_TDATA;
input   weight_V_V_TVALID;
output   weight_V_V_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_V_V_TREADY;
reg out_V_V_TVALID;
reg weight_V_V_TREADY;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [3:0] threshs_m_thresholds_11_address0;
reg    threshs_m_thresholds_11_ce0;
wire   [4:0] threshs_m_thresholds_11_q0;
wire   [3:0] threshs_m_thresholds_10_address0;
reg    threshs_m_thresholds_10_ce0;
wire   [6:0] threshs_m_thresholds_10_q0;
wire   [3:0] threshs_m_thresholds_9_address0;
reg    threshs_m_thresholds_9_ce0;
wire   [7:0] threshs_m_thresholds_9_q0;
wire   [3:0] threshs_m_thresholds_8_address0;
reg    threshs_m_thresholds_8_ce0;
wire   [5:0] threshs_m_thresholds_8_q0;
wire   [3:0] threshs_m_thresholds_7_address0;
reg    threshs_m_thresholds_7_ce0;
wire   [6:0] threshs_m_thresholds_7_q0;
wire   [3:0] threshs_m_thresholds_6_address0;
reg    threshs_m_thresholds_6_ce0;
wire   [7:0] threshs_m_thresholds_6_q0;
wire   [3:0] threshs_m_thresholds_5_address0;
reg    threshs_m_thresholds_5_ce0;
wire   [3:0] threshs_m_thresholds_5_q0;
wire   [3:0] threshs_m_thresholds_4_address0;
reg    threshs_m_thresholds_4_ce0;
wire   [4:0] threshs_m_thresholds_4_q0;
wire   [3:0] threshs_m_thresholds_3_address0;
reg    threshs_m_thresholds_3_ce0;
wire   [5:0] threshs_m_thresholds_3_q0;
wire   [3:0] threshs_m_thresholds_2_address0;
reg    threshs_m_thresholds_2_ce0;
wire   [3:0] threshs_m_thresholds_2_q0;
wire   [3:0] threshs_m_thresholds_1_address0;
reg    threshs_m_thresholds_1_ce0;
wire   [5:0] threshs_m_thresholds_1_q0;
wire   [3:0] threshs_m_thresholds_address0;
reg    threshs_m_thresholds_ce0;
wire   [6:0] threshs_m_thresholds_q0;
reg    in_V_V_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln248_fu_592_p2;
wire   [0:0] icmp_ln252_fu_607_p2;
reg    out_V_V_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] icmp_ln289_reg_3835;
reg   [0:0] icmp_ln289_reg_3835_pp0_iter1_reg;
reg    weight_V_V_TDATA_blk_n;
reg   [6:0] i_0_reg_561;
reg    ap_predicate_op40_read_state2;
reg    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
reg    ap_block_state4_io;
reg    ap_block_pp0_stage0_11001;
wire   [6:0] i_fu_598_p2;
wire   [0:0] icmp_ln271_fu_754_p2;
reg   [0:0] icmp_ln271_reg_3487;
wire   [1:0] wgt_M_instance_0_V_fu_760_p1;
reg  signed [1:0] wgt_M_instance_0_V_reg_3495;
reg  signed [1:0] wgt_M_instance_1_V_reg_3500;
reg  signed [1:0] wgt_M_instance_2_V_reg_3505;
reg  signed [1:0] wgt_M_instance_6_V_reg_3510;
reg  signed [1:0] wgt_M_instance_7_V_reg_3515;
reg  signed [1:0] wgt_M_instance_8_V_reg_3520;
reg  signed [1:0] wgt_M_instance_9_V_reg_3525;
reg  signed [1:0] wgt_M_instance_10_s_reg_3530;
reg  signed [1:0] wgt_M_instance_11_s_reg_3535;
reg  signed [1:0] wgt_M_instance_12_s_reg_3540;
reg  signed [1:0] wgt_M_instance_13_s_reg_3545;
reg  signed [1:0] wgt_M_instance_14_s_reg_3550;
wire   [1:0] trunc_ln647_fu_914_p1;
reg   [1:0] trunc_ln647_reg_3555;
reg   [1:0] arg_V_read_assign_1_reg_3560;
reg   [1:0] arg_V_read_assign_2_reg_3565;
reg   [1:0] arg_V_read_assign_6_reg_3570;
reg   [1:0] arg_V_read_assign_7_reg_3575;
reg   [1:0] arg_V_read_assign_8_reg_3580;
reg   [1:0] arg_V_read_assign_9_reg_3585;
reg   [1:0] arg_V_read_assign_s_reg_3590;
reg   [1:0] arg_V_read_assign_10_reg_3595;
reg   [1:0] arg_V_read_assign_11_reg_3600;
reg   [1:0] arg_V_read_assign_12_reg_3605;
reg   [1:0] arg_V_read_assign_13_reg_3610;
wire   [4:0] add_ln700_10_fu_1140_p2;
reg   [4:0] add_ln700_10_reg_3615;
wire   [4:0] add_ln700_11_fu_1146_p2;
reg   [4:0] add_ln700_11_reg_3620;
reg  signed [1:0] wgt_M_instance_0_V_1_reg_3625;
reg  signed [1:0] wgt_M_instance_1_V_1_reg_3630;
reg  signed [1:0] wgt_M_instance_2_V_1_reg_3635;
reg  signed [1:0] wgt_M_instance_6_V_1_reg_3640;
reg  signed [1:0] wgt_M_instance_7_V_1_reg_3645;
reg  signed [1:0] wgt_M_instance_8_V_1_reg_3650;
reg  signed [1:0] wgt_M_instance_9_V_1_reg_3655;
reg  signed [1:0] wgt_M_instance_10_1_reg_3660;
reg  signed [1:0] wgt_M_instance_11_1_reg_3665;
reg  signed [1:0] wgt_M_instance_12_1_reg_3670;
reg  signed [1:0] wgt_M_instance_13_1_reg_3675;
reg  signed [1:0] wgt_M_instance_14_1_reg_3680;
wire   [4:0] add_ln700_26_fu_1368_p2;
reg   [4:0] add_ln700_26_reg_3685;
wire   [4:0] add_ln700_27_fu_1374_p2;
reg   [4:0] add_ln700_27_reg_3690;
reg  signed [1:0] wgt_M_instance_0_V_2_reg_3695;
reg  signed [1:0] wgt_M_instance_1_V_2_reg_3700;
reg  signed [1:0] wgt_M_instance_2_V_2_reg_3705;
reg  signed [1:0] wgt_M_instance_6_V_2_reg_3710;
reg  signed [1:0] wgt_M_instance_7_V_2_reg_3715;
reg  signed [1:0] wgt_M_instance_8_V_2_reg_3720;
reg  signed [1:0] wgt_M_instance_9_V_2_reg_3725;
reg  signed [1:0] wgt_M_instance_10_2_reg_3730;
reg  signed [1:0] wgt_M_instance_11_2_reg_3735;
reg  signed [1:0] wgt_M_instance_12_2_reg_3740;
reg  signed [1:0] wgt_M_instance_13_2_reg_3745;
reg  signed [1:0] wgt_M_instance_14_2_reg_3750;
wire   [4:0] add_ln700_42_fu_1596_p2;
reg   [4:0] add_ln700_42_reg_3755;
wire   [4:0] add_ln700_43_fu_1602_p2;
reg   [4:0] add_ln700_43_reg_3760;
reg  signed [1:0] wgt_M_instance_0_V_3_reg_3765;
reg  signed [1:0] wgt_M_instance_1_V_3_reg_3770;
reg  signed [1:0] wgt_M_instance_2_V_3_reg_3775;
reg  signed [1:0] wgt_M_instance_6_V_3_reg_3780;
reg  signed [1:0] wgt_M_instance_7_V_3_reg_3785;
reg  signed [1:0] wgt_M_instance_8_V_3_reg_3790;
reg  signed [1:0] wgt_M_instance_9_V_3_reg_3795;
reg  signed [1:0] wgt_M_instance_10_3_reg_3800;
reg  signed [1:0] wgt_M_instance_11_3_reg_3805;
reg  signed [1:0] wgt_M_instance_12_3_reg_3810;
reg  signed [1:0] wgt_M_instance_13_3_reg_3815;
reg  signed [1:0] wgt_M_instance_14_3_reg_3820;
wire   [4:0] add_ln700_58_fu_1824_p2;
reg   [4:0] add_ln700_58_reg_3825;
wire   [4:0] add_ln700_59_fu_1830_p2;
reg   [4:0] add_ln700_59_reg_3830;
wire   [0:0] icmp_ln289_fu_1842_p2;
wire   [8:0] add_ln700_2_fu_2101_p2;
reg   [8:0] add_ln700_2_reg_3839;
wire   [5:0] add_ln700_5_fu_2127_p2;
reg   [5:0] add_ln700_5_reg_3844;
wire   [6:0] add_ln700_14_fu_2185_p2;
reg   [6:0] add_ln700_14_reg_3849;
wire   [8:0] add_ln700_18_fu_2363_p2;
reg   [8:0] add_ln700_18_reg_3854;
wire   [5:0] add_ln700_21_fu_2389_p2;
reg   [5:0] add_ln700_21_reg_3859;
wire   [6:0] add_ln700_30_fu_2447_p2;
reg   [6:0] add_ln700_30_reg_3864;
wire   [8:0] add_ln700_34_fu_2625_p2;
reg   [8:0] add_ln700_34_reg_3869;
wire   [5:0] add_ln700_37_fu_2651_p2;
reg   [5:0] add_ln700_37_reg_3874;
wire   [6:0] add_ln700_46_fu_2709_p2;
reg   [6:0] add_ln700_46_reg_3879;
wire   [8:0] add_ln700_50_fu_2887_p2;
reg   [8:0] add_ln700_50_reg_3884;
wire   [5:0] add_ln700_53_fu_2913_p2;
reg   [5:0] add_ln700_53_reg_3889;
wire   [6:0] add_ln700_62_fu_2971_p2;
reg   [6:0] add_ln700_62_reg_3894;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter1;
reg   [31:0] ap_phi_mux_act_m_val_V_phi_fu_575_p4;
wire   [31:0] ap_phi_reg_pp0_iter0_act_m_val_V_reg_572;
wire   [31:0] inElem_V_fu_632_p6;
wire   [63:0] zext_ln186_fu_2980_p1;
reg   [8:0] accu_V_0_0_0_fu_346;
wire   [8:0] accu_0_0_V_fu_3032_p2;
reg   [8:0] ap_sig_allocacmp_accu_V_0_0_0_load;
reg   [8:0] accu_V_0_1_0_fu_350;
wire   [8:0] accu_0_1_V_fu_3049_p2;
reg   [8:0] ap_sig_allocacmp_accu_V_0_1_0_load;
reg   [8:0] accu_V_0_2_0_fu_354;
wire   [8:0] accu_0_2_V_fu_3066_p2;
reg   [8:0] ap_sig_allocacmp_accu_V_0_2_0_load;
reg   [8:0] accu_V_0_3_0_fu_358;
wire   [8:0] accu_0_3_V_fu_3083_p2;
reg   [8:0] ap_sig_allocacmp_accu_V_0_3_0_load;
reg   [31:0] sf_1_fu_362;
wire   [31:0] sf_fu_1836_p2;
reg   [31:0] nf_assign_fu_366;
wire   [31:0] select_ln301_fu_3008_p3;
reg   [31:0] ap_sig_allocacmp_nf_assign_load_1;
reg   [31:0] inputBuf_3_V_1_fu_370;
wire   [31:0] inputBuf_3_V_9_fu_723_p3;
reg   [31:0] inputBuf_3_V_2_fu_374;
wire   [31:0] inputBuf_3_V_8_fu_715_p3;
reg   [31:0] inputBuf_3_V_3_fu_378;
wire   [31:0] inputBuf_3_V_6_fu_699_p3;
reg   [31:0] inputBuf_3_V_4_fu_382;
wire   [31:0] inputBuf_3_V_fu_683_p3;
reg    ap_block_pp0_stage0_01001;
wire   [1:0] inElem_V_fu_632_p5;
wire   [1:0] trunc_ln321_fu_647_p1;
wire   [0:0] icmp_ln321_2_fu_663_p2;
wire   [0:0] icmp_ln321_1_fu_657_p2;
wire   [0:0] icmp_ln321_fu_651_p2;
wire   [0:0] or_ln321_fu_669_p2;
wire   [31:0] select_ln321_fu_675_p3;
wire   [31:0] select_ln321_2_fu_691_p3;
wire   [31:0] inputBuf_3_V_7_fu_707_p3;
wire  signed [1:0] wgt_M_instance_3_V_fu_784_p4;
wire   [1:0] arg_V_read_assign_3_fu_938_p4;
wire   [1:0] mul_ln1352_3_fu_956_p0;
wire   [3:0] zext_ln215_3_fu_952_p1;
wire  signed [3:0] mul_ln1352_3_fu_956_p2;
wire  signed [1:0] wgt_M_instance_4_V_fu_794_p4;
wire   [1:0] arg_V_read_assign_4_fu_966_p4;
wire   [1:0] mul_ln1352_4_fu_984_p0;
wire   [3:0] zext_ln215_4_fu_980_p1;
wire  signed [3:0] mul_ln1352_4_fu_984_p2;
wire  signed [1:0] wgt_M_instance_5_V_fu_804_p4;
wire   [1:0] arg_V_read_assign_5_fu_994_p4;
wire   [1:0] mul_ln1352_5_fu_1012_p0;
wire   [3:0] zext_ln215_5_fu_1008_p1;
wire  signed [3:0] mul_ln1352_5_fu_1012_p2;
wire  signed [1:0] wgt_M_instance_15_s_fu_904_p4;
wire   [1:0] arg_V_read_assign_14_fu_1112_p4;
wire   [1:0] mul_ln1352_15_fu_1130_p0;
wire   [3:0] zext_ln215_15_fu_1126_p1;
wire  signed [3:0] mul_ln1352_15_fu_1130_p2;
wire  signed [4:0] sext_ln170_3_fu_962_p1;
wire  signed [4:0] sext_ln170_4_fu_990_p1;
wire  signed [4:0] sext_ln700_1_fu_1136_p1;
wire  signed [4:0] sext_ln170_5_fu_1018_p1;
wire  signed [1:0] wgt_M_instance_3_V_1_fu_1182_p4;
wire   [1:0] mul_ln1352_19_fu_1316_p0;
wire  signed [3:0] mul_ln1352_19_fu_1316_p2;
wire  signed [1:0] wgt_M_instance_4_V_1_fu_1192_p4;
wire   [1:0] mul_ln1352_20_fu_1330_p0;
wire  signed [3:0] mul_ln1352_20_fu_1330_p2;
wire  signed [1:0] wgt_M_instance_5_V_1_fu_1202_p4;
wire   [1:0] mul_ln1352_21_fu_1344_p0;
wire  signed [3:0] mul_ln1352_21_fu_1344_p2;
wire  signed [1:0] wgt_M_instance_15_1_fu_1302_p4;
wire   [1:0] mul_ln1352_31_fu_1358_p0;
wire  signed [3:0] mul_ln1352_31_fu_1358_p2;
wire  signed [4:0] sext_ln170_17_fu_1322_p1;
wire  signed [4:0] sext_ln170_18_fu_1336_p1;
wire  signed [4:0] sext_ln700_14_fu_1364_p1;
wire  signed [4:0] sext_ln170_19_fu_1350_p1;
wire  signed [1:0] wgt_M_instance_3_V_2_fu_1410_p4;
wire   [1:0] mul_ln1352_35_fu_1544_p0;
wire  signed [3:0] mul_ln1352_35_fu_1544_p2;
wire  signed [1:0] wgt_M_instance_4_V_2_fu_1420_p4;
wire   [1:0] mul_ln1352_36_fu_1558_p0;
wire  signed [3:0] mul_ln1352_36_fu_1558_p2;
wire  signed [1:0] wgt_M_instance_5_V_2_fu_1430_p4;
wire   [1:0] mul_ln1352_37_fu_1572_p0;
wire  signed [3:0] mul_ln1352_37_fu_1572_p2;
wire  signed [1:0] wgt_M_instance_15_2_fu_1530_p4;
wire   [1:0] mul_ln1352_47_fu_1586_p0;
wire  signed [3:0] mul_ln1352_47_fu_1586_p2;
wire  signed [4:0] sext_ln170_31_fu_1550_p1;
wire  signed [4:0] sext_ln170_32_fu_1564_p1;
wire  signed [4:0] sext_ln700_27_fu_1592_p1;
wire  signed [4:0] sext_ln170_33_fu_1578_p1;
wire  signed [1:0] wgt_M_instance_3_V_3_fu_1638_p4;
wire   [1:0] mul_ln1352_51_fu_1772_p0;
wire  signed [3:0] mul_ln1352_51_fu_1772_p2;
wire  signed [1:0] wgt_M_instance_4_V_3_fu_1648_p4;
wire   [1:0] mul_ln1352_52_fu_1786_p0;
wire  signed [3:0] mul_ln1352_52_fu_1786_p2;
wire  signed [1:0] wgt_M_instance_5_V_3_fu_1658_p4;
wire   [1:0] mul_ln1352_53_fu_1800_p0;
wire  signed [3:0] mul_ln1352_53_fu_1800_p2;
wire  signed [1:0] wgt_M_instance_15_3_fu_1758_p4;
wire   [1:0] mul_ln1352_63_fu_1814_p0;
wire  signed [3:0] mul_ln1352_63_fu_1814_p2;
wire  signed [4:0] sext_ln170_45_fu_1778_p1;
wire  signed [4:0] sext_ln170_46_fu_1792_p1;
wire  signed [4:0] sext_ln700_40_fu_1820_p1;
wire  signed [4:0] sext_ln170_47_fu_1806_p1;
wire   [1:0] mul_ln1352_fu_1899_p0;
wire   [3:0] zext_ln215_fu_1896_p1;
wire  signed [3:0] mul_ln1352_fu_1899_p2;
wire   [1:0] mul_ln1352_1_fu_1915_p0;
wire   [3:0] zext_ln215_1_fu_1912_p1;
wire  signed [3:0] mul_ln1352_1_fu_1915_p2;
wire   [1:0] mul_ln1352_2_fu_1931_p0;
wire   [3:0] zext_ln215_2_fu_1928_p1;
wire  signed [3:0] mul_ln1352_2_fu_1931_p2;
wire   [1:0] mul_ln1352_6_fu_1947_p0;
wire   [3:0] zext_ln215_6_fu_1944_p1;
wire  signed [3:0] mul_ln1352_6_fu_1947_p2;
wire   [1:0] mul_ln1352_7_fu_1963_p0;
wire   [3:0] zext_ln215_7_fu_1960_p1;
wire  signed [3:0] mul_ln1352_7_fu_1963_p2;
wire   [1:0] mul_ln1352_8_fu_1979_p0;
wire   [3:0] zext_ln215_8_fu_1976_p1;
wire  signed [3:0] mul_ln1352_8_fu_1979_p2;
wire   [1:0] mul_ln1352_9_fu_1995_p0;
wire   [3:0] zext_ln215_9_fu_1992_p1;
wire  signed [3:0] mul_ln1352_9_fu_1995_p2;
wire   [1:0] mul_ln1352_10_fu_2011_p0;
wire   [3:0] zext_ln215_10_fu_2008_p1;
wire  signed [3:0] mul_ln1352_10_fu_2011_p2;
wire   [1:0] mul_ln1352_11_fu_2027_p0;
wire   [3:0] zext_ln215_11_fu_2024_p1;
wire  signed [3:0] mul_ln1352_11_fu_2027_p2;
wire   [1:0] mul_ln1352_12_fu_2043_p0;
wire   [3:0] zext_ln215_12_fu_2040_p1;
wire  signed [3:0] mul_ln1352_12_fu_2043_p2;
wire   [1:0] mul_ln1352_13_fu_2059_p0;
wire   [3:0] zext_ln215_13_fu_2056_p1;
wire  signed [3:0] mul_ln1352_13_fu_2059_p2;
wire   [1:0] mul_ln1352_14_fu_2075_p0;
wire   [3:0] zext_ln215_14_fu_2072_p1;
wire  signed [3:0] mul_ln1352_14_fu_2075_p2;
wire  signed [8:0] sext_ln700_fu_2065_p1;
wire   [8:0] select_ln271_3_fu_1886_p3;
wire  signed [4:0] sext_ln170_12_fu_2049_p1;
wire  signed [4:0] sext_ln170_13_fu_2081_p1;
wire   [4:0] add_ln700_1_fu_2091_p2;
wire   [8:0] add_ln700_fu_2085_p2;
wire  signed [8:0] sext_ln700_2_fu_2097_p1;
wire  signed [4:0] sext_ln170_8_fu_1985_p1;
wire  signed [4:0] sext_ln170_11_fu_2033_p1;
wire   [4:0] add_ln700_3_fu_2107_p2;
wire  signed [4:0] sext_ln170_10_fu_2017_p1;
wire  signed [4:0] sext_ln170_7_fu_1969_p1;
wire   [4:0] add_ln700_4_fu_2117_p2;
wire  signed [5:0] sext_ln700_3_fu_2113_p1;
wire  signed [5:0] sext_ln700_4_fu_2123_p1;
wire  signed [4:0] sext_ln170_fu_1905_p1;
wire  signed [4:0] sext_ln170_9_fu_2001_p1;
wire   [4:0] add_ln700_7_fu_2133_p2;
wire  signed [4:0] sext_ln170_1_fu_1921_p1;
wire  signed [4:0] sext_ln170_2_fu_1937_p1;
wire   [4:0] add_ln700_8_fu_2143_p2;
wire  signed [5:0] sext_ln700_6_fu_2139_p1;
wire  signed [5:0] sext_ln700_7_fu_2149_p1;
wire   [5:0] add_ln700_9_fu_2153_p2;
wire  signed [5:0] sext_ln170_6_fu_1953_p1;
wire  signed [5:0] sext_ln700_10_fu_2166_p1;
wire  signed [5:0] sext_ln700_9_fu_2163_p1;
wire   [5:0] add_ln700_12_fu_2169_p2;
wire   [5:0] add_ln700_13_fu_2175_p2;
wire  signed [6:0] sext_ln700_8_fu_2159_p1;
wire  signed [6:0] sext_ln700_11_fu_2181_p1;
wire   [1:0] mul_ln1352_16_fu_2194_p0;
wire  signed [3:0] mul_ln1352_16_fu_2194_p2;
wire   [1:0] mul_ln1352_17_fu_2207_p0;
wire  signed [3:0] mul_ln1352_17_fu_2207_p2;
wire   [1:0] mul_ln1352_18_fu_2220_p0;
wire  signed [3:0] mul_ln1352_18_fu_2220_p2;
wire   [1:0] mul_ln1352_22_fu_2233_p0;
wire  signed [3:0] mul_ln1352_22_fu_2233_p2;
wire   [1:0] mul_ln1352_23_fu_2246_p0;
wire  signed [3:0] mul_ln1352_23_fu_2246_p2;
wire   [1:0] mul_ln1352_24_fu_2259_p0;
wire  signed [3:0] mul_ln1352_24_fu_2259_p2;
wire   [1:0] mul_ln1352_25_fu_2272_p0;
wire  signed [3:0] mul_ln1352_25_fu_2272_p2;
wire   [1:0] mul_ln1352_26_fu_2285_p0;
wire  signed [3:0] mul_ln1352_26_fu_2285_p2;
wire   [1:0] mul_ln1352_27_fu_2298_p0;
wire  signed [3:0] mul_ln1352_27_fu_2298_p2;
wire   [1:0] mul_ln1352_28_fu_2311_p0;
wire  signed [3:0] mul_ln1352_28_fu_2311_p2;
wire   [1:0] mul_ln1352_29_fu_2324_p0;
wire  signed [3:0] mul_ln1352_29_fu_2324_p2;
wire   [1:0] mul_ln1352_30_fu_2337_p0;
wire  signed [3:0] mul_ln1352_30_fu_2337_p2;
wire  signed [8:0] sext_ln700_13_fu_2330_p1;
wire   [8:0] select_ln271_2_fu_1879_p3;
wire  signed [4:0] sext_ln170_26_fu_2317_p1;
wire  signed [4:0] sext_ln170_27_fu_2343_p1;
wire   [4:0] add_ln700_17_fu_2353_p2;
wire   [8:0] add_ln700_16_fu_2347_p2;
wire  signed [8:0] sext_ln700_15_fu_2359_p1;
wire  signed [4:0] sext_ln170_22_fu_2265_p1;
wire  signed [4:0] sext_ln170_25_fu_2304_p1;
wire   [4:0] add_ln700_19_fu_2369_p2;
wire  signed [4:0] sext_ln170_24_fu_2291_p1;
wire  signed [4:0] sext_ln170_21_fu_2252_p1;
wire   [4:0] add_ln700_20_fu_2379_p2;
wire  signed [5:0] sext_ln700_16_fu_2375_p1;
wire  signed [5:0] sext_ln700_17_fu_2385_p1;
wire  signed [4:0] sext_ln170_14_fu_2200_p1;
wire  signed [4:0] sext_ln170_23_fu_2278_p1;
wire   [4:0] add_ln700_23_fu_2395_p2;
wire  signed [4:0] sext_ln170_15_fu_2213_p1;
wire  signed [4:0] sext_ln170_16_fu_2226_p1;
wire   [4:0] add_ln700_24_fu_2405_p2;
wire  signed [5:0] sext_ln700_19_fu_2401_p1;
wire  signed [5:0] sext_ln700_20_fu_2411_p1;
wire   [5:0] add_ln700_25_fu_2415_p2;
wire  signed [5:0] sext_ln170_20_fu_2239_p1;
wire  signed [5:0] sext_ln700_23_fu_2428_p1;
wire  signed [5:0] sext_ln700_22_fu_2425_p1;
wire   [5:0] add_ln700_28_fu_2431_p2;
wire   [5:0] add_ln700_29_fu_2437_p2;
wire  signed [6:0] sext_ln700_21_fu_2421_p1;
wire  signed [6:0] sext_ln700_24_fu_2443_p1;
wire   [1:0] mul_ln1352_32_fu_2456_p0;
wire  signed [3:0] mul_ln1352_32_fu_2456_p2;
wire   [1:0] mul_ln1352_33_fu_2469_p0;
wire  signed [3:0] mul_ln1352_33_fu_2469_p2;
wire   [1:0] mul_ln1352_34_fu_2482_p0;
wire  signed [3:0] mul_ln1352_34_fu_2482_p2;
wire   [1:0] mul_ln1352_38_fu_2495_p0;
wire  signed [3:0] mul_ln1352_38_fu_2495_p2;
wire   [1:0] mul_ln1352_39_fu_2508_p0;
wire  signed [3:0] mul_ln1352_39_fu_2508_p2;
wire   [1:0] mul_ln1352_40_fu_2521_p0;
wire  signed [3:0] mul_ln1352_40_fu_2521_p2;
wire   [1:0] mul_ln1352_41_fu_2534_p0;
wire  signed [3:0] mul_ln1352_41_fu_2534_p2;
wire   [1:0] mul_ln1352_42_fu_2547_p0;
wire  signed [3:0] mul_ln1352_42_fu_2547_p2;
wire   [1:0] mul_ln1352_43_fu_2560_p0;
wire  signed [3:0] mul_ln1352_43_fu_2560_p2;
wire   [1:0] mul_ln1352_44_fu_2573_p0;
wire  signed [3:0] mul_ln1352_44_fu_2573_p2;
wire   [1:0] mul_ln1352_45_fu_2586_p0;
wire  signed [3:0] mul_ln1352_45_fu_2586_p2;
wire   [1:0] mul_ln1352_46_fu_2599_p0;
wire  signed [3:0] mul_ln1352_46_fu_2599_p2;
wire  signed [8:0] sext_ln700_26_fu_2592_p1;
wire   [8:0] select_ln271_1_fu_1872_p3;
wire  signed [4:0] sext_ln170_40_fu_2579_p1;
wire  signed [4:0] sext_ln170_41_fu_2605_p1;
wire   [4:0] add_ln700_33_fu_2615_p2;
wire   [8:0] add_ln700_32_fu_2609_p2;
wire  signed [8:0] sext_ln700_28_fu_2621_p1;
wire  signed [4:0] sext_ln170_36_fu_2527_p1;
wire  signed [4:0] sext_ln170_39_fu_2566_p1;
wire   [4:0] add_ln700_35_fu_2631_p2;
wire  signed [4:0] sext_ln170_38_fu_2553_p1;
wire  signed [4:0] sext_ln170_35_fu_2514_p1;
wire   [4:0] add_ln700_36_fu_2641_p2;
wire  signed [5:0] sext_ln700_29_fu_2637_p1;
wire  signed [5:0] sext_ln700_30_fu_2647_p1;
wire  signed [4:0] sext_ln170_28_fu_2462_p1;
wire  signed [4:0] sext_ln170_37_fu_2540_p1;
wire   [4:0] add_ln700_39_fu_2657_p2;
wire  signed [4:0] sext_ln170_29_fu_2475_p1;
wire  signed [4:0] sext_ln170_30_fu_2488_p1;
wire   [4:0] add_ln700_40_fu_2667_p2;
wire  signed [5:0] sext_ln700_32_fu_2663_p1;
wire  signed [5:0] sext_ln700_33_fu_2673_p1;
wire   [5:0] add_ln700_41_fu_2677_p2;
wire  signed [5:0] sext_ln170_34_fu_2501_p1;
wire  signed [5:0] sext_ln700_36_fu_2690_p1;
wire  signed [5:0] sext_ln700_35_fu_2687_p1;
wire   [5:0] add_ln700_44_fu_2693_p2;
wire   [5:0] add_ln700_45_fu_2699_p2;
wire  signed [6:0] sext_ln700_34_fu_2683_p1;
wire  signed [6:0] sext_ln700_37_fu_2705_p1;
wire   [1:0] mul_ln1352_48_fu_2718_p0;
wire  signed [3:0] mul_ln1352_48_fu_2718_p2;
wire   [1:0] mul_ln1352_49_fu_2731_p0;
wire  signed [3:0] mul_ln1352_49_fu_2731_p2;
wire   [1:0] mul_ln1352_50_fu_2744_p0;
wire  signed [3:0] mul_ln1352_50_fu_2744_p2;
wire   [1:0] mul_ln1352_54_fu_2757_p0;
wire  signed [3:0] mul_ln1352_54_fu_2757_p2;
wire   [1:0] mul_ln1352_55_fu_2770_p0;
wire  signed [3:0] mul_ln1352_55_fu_2770_p2;
wire   [1:0] mul_ln1352_56_fu_2783_p0;
wire  signed [3:0] mul_ln1352_56_fu_2783_p2;
wire   [1:0] mul_ln1352_57_fu_2796_p0;
wire  signed [3:0] mul_ln1352_57_fu_2796_p2;
wire   [1:0] mul_ln1352_58_fu_2809_p0;
wire  signed [3:0] mul_ln1352_58_fu_2809_p2;
wire   [1:0] mul_ln1352_59_fu_2822_p0;
wire  signed [3:0] mul_ln1352_59_fu_2822_p2;
wire   [1:0] mul_ln1352_60_fu_2835_p0;
wire  signed [3:0] mul_ln1352_60_fu_2835_p2;
wire   [1:0] mul_ln1352_61_fu_2848_p0;
wire  signed [3:0] mul_ln1352_61_fu_2848_p2;
wire   [1:0] mul_ln1352_62_fu_2861_p0;
wire  signed [3:0] mul_ln1352_62_fu_2861_p2;
wire  signed [8:0] sext_ln700_39_fu_2854_p1;
wire   [8:0] select_ln271_fu_1865_p3;
wire  signed [4:0] sext_ln170_54_fu_2841_p1;
wire  signed [4:0] sext_ln170_55_fu_2867_p1;
wire   [4:0] add_ln700_49_fu_2877_p2;
wire   [8:0] add_ln700_48_fu_2871_p2;
wire  signed [8:0] sext_ln700_41_fu_2883_p1;
wire  signed [4:0] sext_ln170_50_fu_2789_p1;
wire  signed [4:0] sext_ln170_53_fu_2828_p1;
wire   [4:0] add_ln700_51_fu_2893_p2;
wire  signed [4:0] sext_ln170_52_fu_2815_p1;
wire  signed [4:0] sext_ln170_49_fu_2776_p1;
wire   [4:0] add_ln700_52_fu_2903_p2;
wire  signed [5:0] sext_ln700_42_fu_2899_p1;
wire  signed [5:0] sext_ln700_43_fu_2909_p1;
wire  signed [4:0] sext_ln170_42_fu_2724_p1;
wire  signed [4:0] sext_ln170_51_fu_2802_p1;
wire   [4:0] add_ln700_55_fu_2919_p2;
wire  signed [4:0] sext_ln170_43_fu_2737_p1;
wire  signed [4:0] sext_ln170_44_fu_2750_p1;
wire   [4:0] add_ln700_56_fu_2929_p2;
wire  signed [5:0] sext_ln700_45_fu_2925_p1;
wire  signed [5:0] sext_ln700_46_fu_2935_p1;
wire   [5:0] add_ln700_57_fu_2939_p2;
wire  signed [5:0] sext_ln170_48_fu_2763_p1;
wire  signed [5:0] sext_ln700_49_fu_2952_p1;
wire  signed [5:0] sext_ln700_48_fu_2949_p1;
wire   [5:0] add_ln700_60_fu_2955_p2;
wire   [5:0] add_ln700_61_fu_2961_p2;
wire  signed [6:0] sext_ln700_47_fu_2945_p1;
wire  signed [6:0] sext_ln700_50_fu_2967_p1;
wire   [31:0] nf_fu_2996_p2;
wire   [0:0] icmp_ln301_fu_3002_p2;
wire  signed [8:0] sext_ln700_5_fu_3021_p1;
wire   [8:0] add_ln700_6_fu_3024_p2;
wire  signed [8:0] sext_ln700_12_fu_3029_p1;
wire  signed [8:0] sext_ln700_18_fu_3038_p1;
wire   [8:0] add_ln700_22_fu_3041_p2;
wire  signed [8:0] sext_ln700_25_fu_3046_p1;
wire  signed [8:0] sext_ln700_31_fu_3055_p1;
wire   [8:0] add_ln700_38_fu_3058_p2;
wire  signed [8:0] sext_ln700_38_fu_3063_p1;
wire  signed [8:0] sext_ln700_44_fu_3072_p1;
wire   [8:0] add_ln700_54_fu_3075_p2;
wire  signed [8:0] sext_ln700_51_fu_3080_p1;
wire   [8:0] zext_ln186_1_fu_3109_p1;
wire   [0:0] icmp_ln899_fu_3113_p2;
wire   [0:0] xor_ln899_fu_3119_p2;
wire   [8:0] zext_ln186_2_fu_3129_p1;
wire   [0:0] icmp_ln899_1_fu_3133_p2;
wire   [0:0] xor_ln899_1_fu_3139_p2;
wire   [8:0] zext_ln186_3_fu_3149_p1;
wire   [0:0] icmp_ln899_2_fu_3153_p2;
wire   [0:0] xor_ln899_2_fu_3159_p2;
wire   [1:0] zext_ln700_1_fu_3145_p1;
wire   [1:0] zext_ln700_2_fu_3165_p1;
wire   [1:0] add_ln700_64_fu_3169_p2;
wire   [1:0] zext_ln700_fu_3125_p1;
wire   [8:0] zext_ln186_4_fu_3181_p1;
wire   [0:0] icmp_ln899_3_fu_3185_p2;
wire   [0:0] xor_ln899_3_fu_3191_p2;
wire   [8:0] zext_ln186_5_fu_3201_p1;
wire   [0:0] icmp_ln899_4_fu_3205_p2;
wire   [0:0] xor_ln899_4_fu_3211_p2;
wire   [8:0] zext_ln186_6_fu_3221_p1;
wire   [0:0] icmp_ln899_5_fu_3225_p2;
wire   [0:0] xor_ln899_5_fu_3231_p2;
wire   [1:0] zext_ln700_4_fu_3217_p1;
wire   [1:0] zext_ln700_5_fu_3237_p1;
wire   [1:0] add_ln700_66_fu_3241_p2;
wire   [1:0] zext_ln700_3_fu_3197_p1;
wire   [8:0] zext_ln186_7_fu_3253_p1;
wire   [0:0] icmp_ln899_6_fu_3257_p2;
wire   [0:0] xor_ln899_6_fu_3263_p2;
wire   [8:0] zext_ln186_8_fu_3273_p1;
wire   [0:0] icmp_ln899_7_fu_3277_p2;
wire   [0:0] xor_ln899_7_fu_3283_p2;
wire   [8:0] zext_ln186_9_fu_3293_p1;
wire   [0:0] icmp_ln899_8_fu_3297_p2;
wire   [0:0] xor_ln899_8_fu_3303_p2;
wire   [1:0] zext_ln700_7_fu_3289_p1;
wire   [1:0] zext_ln700_8_fu_3309_p1;
wire   [1:0] add_ln700_68_fu_3313_p2;
wire   [1:0] zext_ln700_6_fu_3269_p1;
wire   [8:0] zext_ln186_10_fu_3325_p1;
wire   [0:0] icmp_ln899_9_fu_3329_p2;
wire   [0:0] xor_ln899_9_fu_3335_p2;
wire   [8:0] zext_ln186_11_fu_3345_p1;
wire   [0:0] icmp_ln899_10_fu_3349_p2;
wire   [0:0] xor_ln899_10_fu_3355_p2;
wire   [8:0] zext_ln186_12_fu_3365_p1;
wire   [0:0] icmp_ln899_11_fu_3369_p2;
wire   [0:0] xor_ln899_11_fu_3375_p2;
wire   [1:0] zext_ln700_10_fu_3361_p1;
wire   [1:0] zext_ln700_11_fu_3381_p1;
wire   [1:0] add_ln700_70_fu_3385_p2;
wire   [1:0] zext_ln700_9_fu_3341_p1;
wire   [1:0] add_ln700_71_fu_3391_p2;
wire   [1:0] add_ln700_69_fu_3319_p2;
wire   [1:0] add_ln700_67_fu_3247_p2;
wire   [1:0] add_ln700_65_fu_3175_p2;
wire    ap_CS_fsm_state5;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

StreamingFCLayer_Batch_1_Matrix_Vector_Actbkb #(
    .DataWidth( 5 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
threshs_m_thresholds_11_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_11_address0),
    .ce0(threshs_m_thresholds_11_ce0),
    .q0(threshs_m_thresholds_11_q0)
);

StreamingFCLayer_Batch_1_Matrix_Vector_Actcud #(
    .DataWidth( 7 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
threshs_m_thresholds_10_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_10_address0),
    .ce0(threshs_m_thresholds_10_ce0),
    .q0(threshs_m_thresholds_10_q0)
);

StreamingFCLayer_Batch_1_Matrix_Vector_ActdEe #(
    .DataWidth( 8 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
threshs_m_thresholds_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_9_address0),
    .ce0(threshs_m_thresholds_9_ce0),
    .q0(threshs_m_thresholds_9_q0)
);

StreamingFCLayer_Batch_1_Matrix_Vector_ActeOg #(
    .DataWidth( 6 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
threshs_m_thresholds_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_8_address0),
    .ce0(threshs_m_thresholds_8_ce0),
    .q0(threshs_m_thresholds_8_q0)
);

StreamingFCLayer_Batch_1_Matrix_Vector_ActfYi #(
    .DataWidth( 7 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
threshs_m_thresholds_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_7_address0),
    .ce0(threshs_m_thresholds_7_ce0),
    .q0(threshs_m_thresholds_7_q0)
);

StreamingFCLayer_Batch_1_Matrix_Vector_Actg8j #(
    .DataWidth( 8 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
threshs_m_thresholds_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_6_address0),
    .ce0(threshs_m_thresholds_6_ce0),
    .q0(threshs_m_thresholds_6_q0)
);

StreamingFCLayer_Batch_1_Matrix_Vector_Acthbi #(
    .DataWidth( 4 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
threshs_m_thresholds_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_5_address0),
    .ce0(threshs_m_thresholds_5_ce0),
    .q0(threshs_m_thresholds_5_q0)
);

StreamingFCLayer_Batch_1_Matrix_Vector_Actibs #(
    .DataWidth( 5 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
threshs_m_thresholds_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_4_address0),
    .ce0(threshs_m_thresholds_4_ce0),
    .q0(threshs_m_thresholds_4_q0)
);

StreamingFCLayer_Batch_1_Matrix_Vector_ActjbC #(
    .DataWidth( 6 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
threshs_m_thresholds_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_3_address0),
    .ce0(threshs_m_thresholds_3_ce0),
    .q0(threshs_m_thresholds_3_q0)
);

StreamingFCLayer_Batch_1_Matrix_Vector_ActkbM #(
    .DataWidth( 4 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
threshs_m_thresholds_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_2_address0),
    .ce0(threshs_m_thresholds_2_ce0),
    .q0(threshs_m_thresholds_2_q0)
);

StreamingFCLayer_Batch_1_Matrix_Vector_ActlbW #(
    .DataWidth( 6 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
threshs_m_thresholds_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_1_address0),
    .ce0(threshs_m_thresholds_1_ce0),
    .q0(threshs_m_thresholds_1_q0)
);

StreamingFCLayer_Batch_1_Matrix_Vector_Actmb6 #(
    .DataWidth( 7 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
threshs_m_thresholds_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_address0),
    .ce0(threshs_m_thresholds_ce0),
    .q0(threshs_m_thresholds_q0)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
StreamingFCLayer_ncg_U1(
    .din0(inputBuf_3_V_1_fu_370),
    .din1(inputBuf_3_V_2_fu_374),
    .din2(inputBuf_3_V_3_fu_378),
    .din3(inputBuf_3_V_4_fu_382),
    .din4(inElem_V_fu_632_p5),
    .dout(inElem_V_fu_632_p6)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U2(
    .din0(mul_ln1352_3_fu_956_p0),
    .din1(wgt_M_instance_3_V_fu_784_p4),
    .dout(mul_ln1352_3_fu_956_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U3(
    .din0(mul_ln1352_4_fu_984_p0),
    .din1(wgt_M_instance_4_V_fu_794_p4),
    .dout(mul_ln1352_4_fu_984_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U4(
    .din0(mul_ln1352_5_fu_1012_p0),
    .din1(wgt_M_instance_5_V_fu_804_p4),
    .dout(mul_ln1352_5_fu_1012_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U5(
    .din0(mul_ln1352_15_fu_1130_p0),
    .din1(wgt_M_instance_15_s_fu_904_p4),
    .dout(mul_ln1352_15_fu_1130_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U6(
    .din0(mul_ln1352_19_fu_1316_p0),
    .din1(wgt_M_instance_3_V_1_fu_1182_p4),
    .dout(mul_ln1352_19_fu_1316_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U7(
    .din0(mul_ln1352_20_fu_1330_p0),
    .din1(wgt_M_instance_4_V_1_fu_1192_p4),
    .dout(mul_ln1352_20_fu_1330_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U8(
    .din0(mul_ln1352_21_fu_1344_p0),
    .din1(wgt_M_instance_5_V_1_fu_1202_p4),
    .dout(mul_ln1352_21_fu_1344_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U9(
    .din0(mul_ln1352_31_fu_1358_p0),
    .din1(wgt_M_instance_15_1_fu_1302_p4),
    .dout(mul_ln1352_31_fu_1358_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U10(
    .din0(mul_ln1352_35_fu_1544_p0),
    .din1(wgt_M_instance_3_V_2_fu_1410_p4),
    .dout(mul_ln1352_35_fu_1544_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U11(
    .din0(mul_ln1352_36_fu_1558_p0),
    .din1(wgt_M_instance_4_V_2_fu_1420_p4),
    .dout(mul_ln1352_36_fu_1558_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U12(
    .din0(mul_ln1352_37_fu_1572_p0),
    .din1(wgt_M_instance_5_V_2_fu_1430_p4),
    .dout(mul_ln1352_37_fu_1572_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U13(
    .din0(mul_ln1352_47_fu_1586_p0),
    .din1(wgt_M_instance_15_2_fu_1530_p4),
    .dout(mul_ln1352_47_fu_1586_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U14(
    .din0(mul_ln1352_51_fu_1772_p0),
    .din1(wgt_M_instance_3_V_3_fu_1638_p4),
    .dout(mul_ln1352_51_fu_1772_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U15(
    .din0(mul_ln1352_52_fu_1786_p0),
    .din1(wgt_M_instance_4_V_3_fu_1648_p4),
    .dout(mul_ln1352_52_fu_1786_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U16(
    .din0(mul_ln1352_53_fu_1800_p0),
    .din1(wgt_M_instance_5_V_3_fu_1658_p4),
    .dout(mul_ln1352_53_fu_1800_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U17(
    .din0(mul_ln1352_63_fu_1814_p0),
    .din1(wgt_M_instance_15_3_fu_1758_p4),
    .dout(mul_ln1352_63_fu_1814_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U18(
    .din0(mul_ln1352_fu_1899_p0),
    .din1(wgt_M_instance_0_V_reg_3495),
    .dout(mul_ln1352_fu_1899_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U19(
    .din0(mul_ln1352_1_fu_1915_p0),
    .din1(wgt_M_instance_1_V_reg_3500),
    .dout(mul_ln1352_1_fu_1915_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U20(
    .din0(mul_ln1352_2_fu_1931_p0),
    .din1(wgt_M_instance_2_V_reg_3505),
    .dout(mul_ln1352_2_fu_1931_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U21(
    .din0(mul_ln1352_6_fu_1947_p0),
    .din1(wgt_M_instance_6_V_reg_3510),
    .dout(mul_ln1352_6_fu_1947_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U22(
    .din0(mul_ln1352_7_fu_1963_p0),
    .din1(wgt_M_instance_7_V_reg_3515),
    .dout(mul_ln1352_7_fu_1963_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U23(
    .din0(mul_ln1352_8_fu_1979_p0),
    .din1(wgt_M_instance_8_V_reg_3520),
    .dout(mul_ln1352_8_fu_1979_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U24(
    .din0(mul_ln1352_9_fu_1995_p0),
    .din1(wgt_M_instance_9_V_reg_3525),
    .dout(mul_ln1352_9_fu_1995_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U25(
    .din0(mul_ln1352_10_fu_2011_p0),
    .din1(wgt_M_instance_10_s_reg_3530),
    .dout(mul_ln1352_10_fu_2011_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U26(
    .din0(mul_ln1352_11_fu_2027_p0),
    .din1(wgt_M_instance_11_s_reg_3535),
    .dout(mul_ln1352_11_fu_2027_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U27(
    .din0(mul_ln1352_12_fu_2043_p0),
    .din1(wgt_M_instance_12_s_reg_3540),
    .dout(mul_ln1352_12_fu_2043_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U28(
    .din0(mul_ln1352_13_fu_2059_p0),
    .din1(wgt_M_instance_13_s_reg_3545),
    .dout(mul_ln1352_13_fu_2059_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U29(
    .din0(mul_ln1352_14_fu_2075_p0),
    .din1(wgt_M_instance_14_s_reg_3550),
    .dout(mul_ln1352_14_fu_2075_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U30(
    .din0(mul_ln1352_16_fu_2194_p0),
    .din1(wgt_M_instance_0_V_1_reg_3625),
    .dout(mul_ln1352_16_fu_2194_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U31(
    .din0(mul_ln1352_17_fu_2207_p0),
    .din1(wgt_M_instance_1_V_1_reg_3630),
    .dout(mul_ln1352_17_fu_2207_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U32(
    .din0(mul_ln1352_18_fu_2220_p0),
    .din1(wgt_M_instance_2_V_1_reg_3635),
    .dout(mul_ln1352_18_fu_2220_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U33(
    .din0(mul_ln1352_22_fu_2233_p0),
    .din1(wgt_M_instance_6_V_1_reg_3640),
    .dout(mul_ln1352_22_fu_2233_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U34(
    .din0(mul_ln1352_23_fu_2246_p0),
    .din1(wgt_M_instance_7_V_1_reg_3645),
    .dout(mul_ln1352_23_fu_2246_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U35(
    .din0(mul_ln1352_24_fu_2259_p0),
    .din1(wgt_M_instance_8_V_1_reg_3650),
    .dout(mul_ln1352_24_fu_2259_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U36(
    .din0(mul_ln1352_25_fu_2272_p0),
    .din1(wgt_M_instance_9_V_1_reg_3655),
    .dout(mul_ln1352_25_fu_2272_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U37(
    .din0(mul_ln1352_26_fu_2285_p0),
    .din1(wgt_M_instance_10_1_reg_3660),
    .dout(mul_ln1352_26_fu_2285_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U38(
    .din0(mul_ln1352_27_fu_2298_p0),
    .din1(wgt_M_instance_11_1_reg_3665),
    .dout(mul_ln1352_27_fu_2298_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U39(
    .din0(mul_ln1352_28_fu_2311_p0),
    .din1(wgt_M_instance_12_1_reg_3670),
    .dout(mul_ln1352_28_fu_2311_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U40(
    .din0(mul_ln1352_29_fu_2324_p0),
    .din1(wgt_M_instance_13_1_reg_3675),
    .dout(mul_ln1352_29_fu_2324_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U41(
    .din0(mul_ln1352_30_fu_2337_p0),
    .din1(wgt_M_instance_14_1_reg_3680),
    .dout(mul_ln1352_30_fu_2337_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U42(
    .din0(mul_ln1352_32_fu_2456_p0),
    .din1(wgt_M_instance_0_V_2_reg_3695),
    .dout(mul_ln1352_32_fu_2456_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U43(
    .din0(mul_ln1352_33_fu_2469_p0),
    .din1(wgt_M_instance_1_V_2_reg_3700),
    .dout(mul_ln1352_33_fu_2469_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U44(
    .din0(mul_ln1352_34_fu_2482_p0),
    .din1(wgt_M_instance_2_V_2_reg_3705),
    .dout(mul_ln1352_34_fu_2482_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U45(
    .din0(mul_ln1352_38_fu_2495_p0),
    .din1(wgt_M_instance_6_V_2_reg_3710),
    .dout(mul_ln1352_38_fu_2495_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U46(
    .din0(mul_ln1352_39_fu_2508_p0),
    .din1(wgt_M_instance_7_V_2_reg_3715),
    .dout(mul_ln1352_39_fu_2508_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U47(
    .din0(mul_ln1352_40_fu_2521_p0),
    .din1(wgt_M_instance_8_V_2_reg_3720),
    .dout(mul_ln1352_40_fu_2521_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U48(
    .din0(mul_ln1352_41_fu_2534_p0),
    .din1(wgt_M_instance_9_V_2_reg_3725),
    .dout(mul_ln1352_41_fu_2534_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U49(
    .din0(mul_ln1352_42_fu_2547_p0),
    .din1(wgt_M_instance_10_2_reg_3730),
    .dout(mul_ln1352_42_fu_2547_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U50(
    .din0(mul_ln1352_43_fu_2560_p0),
    .din1(wgt_M_instance_11_2_reg_3735),
    .dout(mul_ln1352_43_fu_2560_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U51(
    .din0(mul_ln1352_44_fu_2573_p0),
    .din1(wgt_M_instance_12_2_reg_3740),
    .dout(mul_ln1352_44_fu_2573_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U52(
    .din0(mul_ln1352_45_fu_2586_p0),
    .din1(wgt_M_instance_13_2_reg_3745),
    .dout(mul_ln1352_45_fu_2586_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U53(
    .din0(mul_ln1352_46_fu_2599_p0),
    .din1(wgt_M_instance_14_2_reg_3750),
    .dout(mul_ln1352_46_fu_2599_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U54(
    .din0(mul_ln1352_48_fu_2718_p0),
    .din1(wgt_M_instance_0_V_3_reg_3765),
    .dout(mul_ln1352_48_fu_2718_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U55(
    .din0(mul_ln1352_49_fu_2731_p0),
    .din1(wgt_M_instance_1_V_3_reg_3770),
    .dout(mul_ln1352_49_fu_2731_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U56(
    .din0(mul_ln1352_50_fu_2744_p0),
    .din1(wgt_M_instance_2_V_3_reg_3775),
    .dout(mul_ln1352_50_fu_2744_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U57(
    .din0(mul_ln1352_54_fu_2757_p0),
    .din1(wgt_M_instance_6_V_3_reg_3780),
    .dout(mul_ln1352_54_fu_2757_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U58(
    .din0(mul_ln1352_55_fu_2770_p0),
    .din1(wgt_M_instance_7_V_3_reg_3785),
    .dout(mul_ln1352_55_fu_2770_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U59(
    .din0(mul_ln1352_56_fu_2783_p0),
    .din1(wgt_M_instance_8_V_3_reg_3790),
    .dout(mul_ln1352_56_fu_2783_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U60(
    .din0(mul_ln1352_57_fu_2796_p0),
    .din1(wgt_M_instance_9_V_3_reg_3795),
    .dout(mul_ln1352_57_fu_2796_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U61(
    .din0(mul_ln1352_58_fu_2809_p0),
    .din1(wgt_M_instance_10_3_reg_3800),
    .dout(mul_ln1352_58_fu_2809_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U62(
    .din0(mul_ln1352_59_fu_2822_p0),
    .din1(wgt_M_instance_11_3_reg_3805),
    .dout(mul_ln1352_59_fu_2822_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U63(
    .din0(mul_ln1352_60_fu_2835_p0),
    .din1(wgt_M_instance_12_3_reg_3810),
    .dout(mul_ln1352_60_fu_2835_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U64(
    .din0(mul_ln1352_61_fu_2848_p0),
    .din1(wgt_M_instance_13_3_reg_3815),
    .dout(mul_ln1352_61_fu_2848_p2)
);

StreamingFCLayer_Batch_1_StreamingFCLayer_ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
StreamingFCLayer_ocq_U65(
    .din0(mul_ln1352_62_fu_2861_p0),
    .din1(wgt_M_instance_14_3_reg_3820),
    .dout(mul_ln1352_62_fu_2861_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln248_fu_592_p2 == 1'd0))) begin
        i_0_reg_561 <= i_fu_598_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_0_reg_561 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln289_reg_3835 == 1'd1))) begin
        nf_assign_fu_366 <= select_ln301_fu_3008_p3;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        nf_assign_fu_366 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln289_fu_1842_p2 == 1'd0) & (icmp_ln248_fu_592_p2 == 1'd0))) begin
        sf_1_fu_362 <= sf_fu_1836_p2;
    end else if ((((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln289_fu_1842_p2 == 1'd1) & (icmp_ln248_fu_592_p2 == 1'd0)))) begin
        sf_1_fu_362 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        accu_V_0_0_0_fu_346 <= accu_0_0_V_fu_3032_p2;
        accu_V_0_1_0_fu_350 <= accu_0_1_V_fu_3049_p2;
        accu_V_0_2_0_fu_354 <= accu_0_2_V_fu_3066_p2;
        accu_V_0_3_0_fu_358 <= accu_0_3_V_fu_3083_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln248_fu_592_p2 == 1'd0))) begin
        add_ln700_10_reg_3615 <= add_ln700_10_fu_1140_p2;
        add_ln700_11_reg_3620 <= add_ln700_11_fu_1146_p2;
        add_ln700_26_reg_3685 <= add_ln700_26_fu_1368_p2;
        add_ln700_27_reg_3690 <= add_ln700_27_fu_1374_p2;
        add_ln700_42_reg_3755 <= add_ln700_42_fu_1596_p2;
        add_ln700_43_reg_3760 <= add_ln700_43_fu_1602_p2;
        add_ln700_58_reg_3825 <= add_ln700_58_fu_1824_p2;
        add_ln700_59_reg_3830 <= add_ln700_59_fu_1830_p2;
        arg_V_read_assign_10_reg_3595 <= {{ap_phi_mux_act_m_val_V_phi_fu_575_p4[23:22]}};
        arg_V_read_assign_11_reg_3600 <= {{ap_phi_mux_act_m_val_V_phi_fu_575_p4[25:24]}};
        arg_V_read_assign_12_reg_3605 <= {{ap_phi_mux_act_m_val_V_phi_fu_575_p4[27:26]}};
        arg_V_read_assign_13_reg_3610 <= {{ap_phi_mux_act_m_val_V_phi_fu_575_p4[29:28]}};
        arg_V_read_assign_1_reg_3560 <= {{ap_phi_mux_act_m_val_V_phi_fu_575_p4[3:2]}};
        arg_V_read_assign_2_reg_3565 <= {{ap_phi_mux_act_m_val_V_phi_fu_575_p4[5:4]}};
        arg_V_read_assign_6_reg_3570 <= {{ap_phi_mux_act_m_val_V_phi_fu_575_p4[13:12]}};
        arg_V_read_assign_7_reg_3575 <= {{ap_phi_mux_act_m_val_V_phi_fu_575_p4[15:14]}};
        arg_V_read_assign_8_reg_3580 <= {{ap_phi_mux_act_m_val_V_phi_fu_575_p4[17:16]}};
        arg_V_read_assign_9_reg_3585 <= {{ap_phi_mux_act_m_val_V_phi_fu_575_p4[19:18]}};
        arg_V_read_assign_s_reg_3590 <= {{ap_phi_mux_act_m_val_V_phi_fu_575_p4[21:20]}};
        icmp_ln271_reg_3487 <= icmp_ln271_fu_754_p2;
        icmp_ln289_reg_3835 <= icmp_ln289_fu_1842_p2;
        trunc_ln647_reg_3555 <= trunc_ln647_fu_914_p1;
        wgt_M_instance_0_V_1_reg_3625 <= {{weight_V_V_TDATA[33:32]}};
        wgt_M_instance_0_V_2_reg_3695 <= {{weight_V_V_TDATA[65:64]}};
        wgt_M_instance_0_V_3_reg_3765 <= {{weight_V_V_TDATA[97:96]}};
        wgt_M_instance_0_V_reg_3495 <= wgt_M_instance_0_V_fu_760_p1;
        wgt_M_instance_10_1_reg_3660 <= {{weight_V_V_TDATA[53:52]}};
        wgt_M_instance_10_2_reg_3730 <= {{weight_V_V_TDATA[85:84]}};
        wgt_M_instance_10_3_reg_3800 <= {{weight_V_V_TDATA[117:116]}};
        wgt_M_instance_10_s_reg_3530 <= {{weight_V_V_TDATA[21:20]}};
        wgt_M_instance_11_1_reg_3665 <= {{weight_V_V_TDATA[55:54]}};
        wgt_M_instance_11_2_reg_3735 <= {{weight_V_V_TDATA[87:86]}};
        wgt_M_instance_11_3_reg_3805 <= {{weight_V_V_TDATA[119:118]}};
        wgt_M_instance_11_s_reg_3535 <= {{weight_V_V_TDATA[23:22]}};
        wgt_M_instance_12_1_reg_3670 <= {{weight_V_V_TDATA[57:56]}};
        wgt_M_instance_12_2_reg_3740 <= {{weight_V_V_TDATA[89:88]}};
        wgt_M_instance_12_3_reg_3810 <= {{weight_V_V_TDATA[121:120]}};
        wgt_M_instance_12_s_reg_3540 <= {{weight_V_V_TDATA[25:24]}};
        wgt_M_instance_13_1_reg_3675 <= {{weight_V_V_TDATA[59:58]}};
        wgt_M_instance_13_2_reg_3745 <= {{weight_V_V_TDATA[91:90]}};
        wgt_M_instance_13_3_reg_3815 <= {{weight_V_V_TDATA[123:122]}};
        wgt_M_instance_13_s_reg_3545 <= {{weight_V_V_TDATA[27:26]}};
        wgt_M_instance_14_1_reg_3680 <= {{weight_V_V_TDATA[61:60]}};
        wgt_M_instance_14_2_reg_3750 <= {{weight_V_V_TDATA[93:92]}};
        wgt_M_instance_14_3_reg_3820 <= {{weight_V_V_TDATA[125:124]}};
        wgt_M_instance_14_s_reg_3550 <= {{weight_V_V_TDATA[29:28]}};
        wgt_M_instance_1_V_1_reg_3630 <= {{weight_V_V_TDATA[35:34]}};
        wgt_M_instance_1_V_2_reg_3700 <= {{weight_V_V_TDATA[67:66]}};
        wgt_M_instance_1_V_3_reg_3770 <= {{weight_V_V_TDATA[99:98]}};
        wgt_M_instance_1_V_reg_3500 <= {{weight_V_V_TDATA[3:2]}};
        wgt_M_instance_2_V_1_reg_3635 <= {{weight_V_V_TDATA[37:36]}};
        wgt_M_instance_2_V_2_reg_3705 <= {{weight_V_V_TDATA[69:68]}};
        wgt_M_instance_2_V_3_reg_3775 <= {{weight_V_V_TDATA[101:100]}};
        wgt_M_instance_2_V_reg_3505 <= {{weight_V_V_TDATA[5:4]}};
        wgt_M_instance_6_V_1_reg_3640 <= {{weight_V_V_TDATA[45:44]}};
        wgt_M_instance_6_V_2_reg_3710 <= {{weight_V_V_TDATA[77:76]}};
        wgt_M_instance_6_V_3_reg_3780 <= {{weight_V_V_TDATA[109:108]}};
        wgt_M_instance_6_V_reg_3510 <= {{weight_V_V_TDATA[13:12]}};
        wgt_M_instance_7_V_1_reg_3645 <= {{weight_V_V_TDATA[47:46]}};
        wgt_M_instance_7_V_2_reg_3715 <= {{weight_V_V_TDATA[79:78]}};
        wgt_M_instance_7_V_3_reg_3785 <= {{weight_V_V_TDATA[111:110]}};
        wgt_M_instance_7_V_reg_3515 <= {{weight_V_V_TDATA[15:14]}};
        wgt_M_instance_8_V_1_reg_3650 <= {{weight_V_V_TDATA[49:48]}};
        wgt_M_instance_8_V_2_reg_3720 <= {{weight_V_V_TDATA[81:80]}};
        wgt_M_instance_8_V_3_reg_3790 <= {{weight_V_V_TDATA[113:112]}};
        wgt_M_instance_8_V_reg_3520 <= {{weight_V_V_TDATA[17:16]}};
        wgt_M_instance_9_V_1_reg_3655 <= {{weight_V_V_TDATA[51:50]}};
        wgt_M_instance_9_V_2_reg_3725 <= {{weight_V_V_TDATA[83:82]}};
        wgt_M_instance_9_V_3_reg_3795 <= {{weight_V_V_TDATA[115:114]}};
        wgt_M_instance_9_V_reg_3525 <= {{weight_V_V_TDATA[19:18]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln700_14_reg_3849 <= add_ln700_14_fu_2185_p2;
        add_ln700_18_reg_3854 <= add_ln700_18_fu_2363_p2;
        add_ln700_21_reg_3859 <= add_ln700_21_fu_2389_p2;
        add_ln700_2_reg_3839 <= add_ln700_2_fu_2101_p2;
        add_ln700_30_reg_3864 <= add_ln700_30_fu_2447_p2;
        add_ln700_34_reg_3869 <= add_ln700_34_fu_2625_p2;
        add_ln700_37_reg_3874 <= add_ln700_37_fu_2651_p2;
        add_ln700_46_reg_3879 <= add_ln700_46_fu_2709_p2;
        add_ln700_50_reg_3884 <= add_ln700_50_fu_2887_p2;
        add_ln700_53_reg_3889 <= add_ln700_53_fu_2913_p2;
        add_ln700_5_reg_3844 <= add_ln700_5_fu_2127_p2;
        add_ln700_62_reg_3894 <= add_ln700_62_fu_2971_p2;
        icmp_ln289_reg_3835_pp0_iter1_reg <= icmp_ln289_reg_3835;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln252_fu_607_p2 == 1'd1) & (icmp_ln248_fu_592_p2 == 1'd0))) begin
        inputBuf_3_V_1_fu_370 <= inputBuf_3_V_9_fu_723_p3;
        inputBuf_3_V_2_fu_374 <= inputBuf_3_V_8_fu_715_p3;
        inputBuf_3_V_3_fu_378 <= inputBuf_3_V_6_fu_699_p3;
        inputBuf_3_V_4_fu_382 <= inputBuf_3_V_fu_683_p3;
    end
end

always @ (*) begin
    if ((icmp_ln248_fu_592_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln248_fu_592_p2 == 1'd0)) begin
        if ((icmp_ln252_fu_607_p2 == 1'd0)) begin
            ap_phi_mux_act_m_val_V_phi_fu_575_p4 = inElem_V_fu_632_p6;
        end else if ((icmp_ln252_fu_607_p2 == 1'd1)) begin
            ap_phi_mux_act_m_val_V_phi_fu_575_p4 = in_V_V_TDATA;
        end else begin
            ap_phi_mux_act_m_val_V_phi_fu_575_p4 = ap_phi_reg_pp0_iter0_act_m_val_V_reg_572;
        end
    end else begin
        ap_phi_mux_act_m_val_V_phi_fu_575_p4 = ap_phi_reg_pp0_iter0_act_m_val_V_reg_572;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_accu_V_0_0_0_load = accu_0_0_V_fu_3032_p2;
    end else begin
        ap_sig_allocacmp_accu_V_0_0_0_load = accu_V_0_0_0_fu_346;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_accu_V_0_1_0_load = accu_0_1_V_fu_3049_p2;
    end else begin
        ap_sig_allocacmp_accu_V_0_1_0_load = accu_V_0_1_0_fu_350;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_accu_V_0_2_0_load = accu_0_2_V_fu_3066_p2;
    end else begin
        ap_sig_allocacmp_accu_V_0_2_0_load = accu_V_0_2_0_fu_354;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_accu_V_0_3_0_load = accu_0_3_V_fu_3083_p2;
    end else begin
        ap_sig_allocacmp_accu_V_0_3_0_load = accu_V_0_3_0_fu_358;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln289_reg_3835 == 1'd1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_nf_assign_load_1 = select_ln301_fu_3008_p3;
    end else begin
        ap_sig_allocacmp_nf_assign_load_1 = nf_assign_fu_366;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln252_fu_607_p2 == 1'd1) & (icmp_ln248_fu_592_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        in_V_V_TDATA_blk_n = in_V_V_TVALID;
    end else begin
        in_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op40_read_state2 == 1'b1))) begin
        in_V_V_TREADY = 1'b1;
    end else begin
        in_V_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln289_reg_3835_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0))) begin
        out_V_V_TDATA_blk_n = out_V_V_TREADY;
    end else begin
        out_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln289_reg_3835_pp0_iter1_reg == 1'd1))) begin
        out_V_V_TVALID = 1'b1;
    end else begin
        out_V_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_10_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_11_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_1_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_2_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_3_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_4_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_5_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_6_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_7_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_8_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_9_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        threshs_m_thresholds_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln248_fu_592_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        weight_V_V_TDATA_blk_n = weight_V_V_TVALID;
    end else begin
        weight_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln248_fu_592_p2 == 1'd0))) begin
        weight_V_V_TREADY = 1'b1;
    end else begin
        weight_V_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln248_fu_592_p2 == 1'd1)) & ~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln248_fu_592_p2 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign accu_0_0_V_fu_3032_p2 = ($signed(add_ln700_6_fu_3024_p2) + $signed(sext_ln700_12_fu_3029_p1));

assign accu_0_1_V_fu_3049_p2 = ($signed(add_ln700_22_fu_3041_p2) + $signed(sext_ln700_25_fu_3046_p1));

assign accu_0_2_V_fu_3066_p2 = ($signed(add_ln700_38_fu_3058_p2) + $signed(sext_ln700_38_fu_3063_p1));

assign accu_0_3_V_fu_3083_p2 = ($signed(add_ln700_54_fu_3075_p2) + $signed(sext_ln700_51_fu_3080_p1));

assign add_ln700_10_fu_1140_p2 = ($signed(sext_ln170_3_fu_962_p1) + $signed(sext_ln170_4_fu_990_p1));

assign add_ln700_11_fu_1146_p2 = ($signed(sext_ln700_1_fu_1136_p1) + $signed(sext_ln170_5_fu_1018_p1));

assign add_ln700_12_fu_2169_p2 = ($signed(sext_ln170_6_fu_1953_p1) + $signed(sext_ln700_10_fu_2166_p1));

assign add_ln700_13_fu_2175_p2 = ($signed(sext_ln700_9_fu_2163_p1) + $signed(add_ln700_12_fu_2169_p2));

assign add_ln700_14_fu_2185_p2 = ($signed(sext_ln700_8_fu_2159_p1) + $signed(sext_ln700_11_fu_2181_p1));

assign add_ln700_16_fu_2347_p2 = ($signed(sext_ln700_13_fu_2330_p1) + $signed(select_ln271_2_fu_1879_p3));

assign add_ln700_17_fu_2353_p2 = ($signed(sext_ln170_26_fu_2317_p1) + $signed(sext_ln170_27_fu_2343_p1));

assign add_ln700_18_fu_2363_p2 = ($signed(add_ln700_16_fu_2347_p2) + $signed(sext_ln700_15_fu_2359_p1));

assign add_ln700_19_fu_2369_p2 = ($signed(sext_ln170_22_fu_2265_p1) + $signed(sext_ln170_25_fu_2304_p1));

assign add_ln700_1_fu_2091_p2 = ($signed(sext_ln170_12_fu_2049_p1) + $signed(sext_ln170_13_fu_2081_p1));

assign add_ln700_20_fu_2379_p2 = ($signed(sext_ln170_24_fu_2291_p1) + $signed(sext_ln170_21_fu_2252_p1));

assign add_ln700_21_fu_2389_p2 = ($signed(sext_ln700_16_fu_2375_p1) + $signed(sext_ln700_17_fu_2385_p1));

assign add_ln700_22_fu_3041_p2 = ($signed(add_ln700_18_reg_3854) + $signed(sext_ln700_18_fu_3038_p1));

assign add_ln700_23_fu_2395_p2 = ($signed(sext_ln170_14_fu_2200_p1) + $signed(sext_ln170_23_fu_2278_p1));

assign add_ln700_24_fu_2405_p2 = ($signed(sext_ln170_15_fu_2213_p1) + $signed(sext_ln170_16_fu_2226_p1));

assign add_ln700_25_fu_2415_p2 = ($signed(sext_ln700_19_fu_2401_p1) + $signed(sext_ln700_20_fu_2411_p1));

assign add_ln700_26_fu_1368_p2 = ($signed(sext_ln170_17_fu_1322_p1) + $signed(sext_ln170_18_fu_1336_p1));

assign add_ln700_27_fu_1374_p2 = ($signed(sext_ln700_14_fu_1364_p1) + $signed(sext_ln170_19_fu_1350_p1));

assign add_ln700_28_fu_2431_p2 = ($signed(sext_ln170_20_fu_2239_p1) + $signed(sext_ln700_23_fu_2428_p1));

assign add_ln700_29_fu_2437_p2 = ($signed(sext_ln700_22_fu_2425_p1) + $signed(add_ln700_28_fu_2431_p2));

assign add_ln700_2_fu_2101_p2 = ($signed(add_ln700_fu_2085_p2) + $signed(sext_ln700_2_fu_2097_p1));

assign add_ln700_30_fu_2447_p2 = ($signed(sext_ln700_21_fu_2421_p1) + $signed(sext_ln700_24_fu_2443_p1));

assign add_ln700_32_fu_2609_p2 = ($signed(sext_ln700_26_fu_2592_p1) + $signed(select_ln271_1_fu_1872_p3));

assign add_ln700_33_fu_2615_p2 = ($signed(sext_ln170_40_fu_2579_p1) + $signed(sext_ln170_41_fu_2605_p1));

assign add_ln700_34_fu_2625_p2 = ($signed(add_ln700_32_fu_2609_p2) + $signed(sext_ln700_28_fu_2621_p1));

assign add_ln700_35_fu_2631_p2 = ($signed(sext_ln170_36_fu_2527_p1) + $signed(sext_ln170_39_fu_2566_p1));

assign add_ln700_36_fu_2641_p2 = ($signed(sext_ln170_38_fu_2553_p1) + $signed(sext_ln170_35_fu_2514_p1));

assign add_ln700_37_fu_2651_p2 = ($signed(sext_ln700_29_fu_2637_p1) + $signed(sext_ln700_30_fu_2647_p1));

assign add_ln700_38_fu_3058_p2 = ($signed(add_ln700_34_reg_3869) + $signed(sext_ln700_31_fu_3055_p1));

assign add_ln700_39_fu_2657_p2 = ($signed(sext_ln170_28_fu_2462_p1) + $signed(sext_ln170_37_fu_2540_p1));

assign add_ln700_3_fu_2107_p2 = ($signed(sext_ln170_8_fu_1985_p1) + $signed(sext_ln170_11_fu_2033_p1));

assign add_ln700_40_fu_2667_p2 = ($signed(sext_ln170_29_fu_2475_p1) + $signed(sext_ln170_30_fu_2488_p1));

assign add_ln700_41_fu_2677_p2 = ($signed(sext_ln700_32_fu_2663_p1) + $signed(sext_ln700_33_fu_2673_p1));

assign add_ln700_42_fu_1596_p2 = ($signed(sext_ln170_31_fu_1550_p1) + $signed(sext_ln170_32_fu_1564_p1));

assign add_ln700_43_fu_1602_p2 = ($signed(sext_ln700_27_fu_1592_p1) + $signed(sext_ln170_33_fu_1578_p1));

assign add_ln700_44_fu_2693_p2 = ($signed(sext_ln170_34_fu_2501_p1) + $signed(sext_ln700_36_fu_2690_p1));

assign add_ln700_45_fu_2699_p2 = ($signed(sext_ln700_35_fu_2687_p1) + $signed(add_ln700_44_fu_2693_p2));

assign add_ln700_46_fu_2709_p2 = ($signed(sext_ln700_34_fu_2683_p1) + $signed(sext_ln700_37_fu_2705_p1));

assign add_ln700_48_fu_2871_p2 = ($signed(sext_ln700_39_fu_2854_p1) + $signed(select_ln271_fu_1865_p3));

assign add_ln700_49_fu_2877_p2 = ($signed(sext_ln170_54_fu_2841_p1) + $signed(sext_ln170_55_fu_2867_p1));

assign add_ln700_4_fu_2117_p2 = ($signed(sext_ln170_10_fu_2017_p1) + $signed(sext_ln170_7_fu_1969_p1));

assign add_ln700_50_fu_2887_p2 = ($signed(add_ln700_48_fu_2871_p2) + $signed(sext_ln700_41_fu_2883_p1));

assign add_ln700_51_fu_2893_p2 = ($signed(sext_ln170_50_fu_2789_p1) + $signed(sext_ln170_53_fu_2828_p1));

assign add_ln700_52_fu_2903_p2 = ($signed(sext_ln170_52_fu_2815_p1) + $signed(sext_ln170_49_fu_2776_p1));

assign add_ln700_53_fu_2913_p2 = ($signed(sext_ln700_42_fu_2899_p1) + $signed(sext_ln700_43_fu_2909_p1));

assign add_ln700_54_fu_3075_p2 = ($signed(add_ln700_50_reg_3884) + $signed(sext_ln700_44_fu_3072_p1));

assign add_ln700_55_fu_2919_p2 = ($signed(sext_ln170_42_fu_2724_p1) + $signed(sext_ln170_51_fu_2802_p1));

assign add_ln700_56_fu_2929_p2 = ($signed(sext_ln170_43_fu_2737_p1) + $signed(sext_ln170_44_fu_2750_p1));

assign add_ln700_57_fu_2939_p2 = ($signed(sext_ln700_45_fu_2925_p1) + $signed(sext_ln700_46_fu_2935_p1));

assign add_ln700_58_fu_1824_p2 = ($signed(sext_ln170_45_fu_1778_p1) + $signed(sext_ln170_46_fu_1792_p1));

assign add_ln700_59_fu_1830_p2 = ($signed(sext_ln700_40_fu_1820_p1) + $signed(sext_ln170_47_fu_1806_p1));

assign add_ln700_5_fu_2127_p2 = ($signed(sext_ln700_3_fu_2113_p1) + $signed(sext_ln700_4_fu_2123_p1));

assign add_ln700_60_fu_2955_p2 = ($signed(sext_ln170_48_fu_2763_p1) + $signed(sext_ln700_49_fu_2952_p1));

assign add_ln700_61_fu_2961_p2 = ($signed(sext_ln700_48_fu_2949_p1) + $signed(add_ln700_60_fu_2955_p2));

assign add_ln700_62_fu_2971_p2 = ($signed(sext_ln700_47_fu_2945_p1) + $signed(sext_ln700_50_fu_2967_p1));

assign add_ln700_64_fu_3169_p2 = (zext_ln700_1_fu_3145_p1 + zext_ln700_2_fu_3165_p1);

assign add_ln700_65_fu_3175_p2 = (add_ln700_64_fu_3169_p2 + zext_ln700_fu_3125_p1);

assign add_ln700_66_fu_3241_p2 = (zext_ln700_4_fu_3217_p1 + zext_ln700_5_fu_3237_p1);

assign add_ln700_67_fu_3247_p2 = (add_ln700_66_fu_3241_p2 + zext_ln700_3_fu_3197_p1);

assign add_ln700_68_fu_3313_p2 = (zext_ln700_7_fu_3289_p1 + zext_ln700_8_fu_3309_p1);

assign add_ln700_69_fu_3319_p2 = (add_ln700_68_fu_3313_p2 + zext_ln700_6_fu_3269_p1);

assign add_ln700_6_fu_3024_p2 = ($signed(add_ln700_2_reg_3839) + $signed(sext_ln700_5_fu_3021_p1));

assign add_ln700_70_fu_3385_p2 = (zext_ln700_10_fu_3361_p1 + zext_ln700_11_fu_3381_p1);

assign add_ln700_71_fu_3391_p2 = (add_ln700_70_fu_3385_p2 + zext_ln700_9_fu_3341_p1);

assign add_ln700_7_fu_2133_p2 = ($signed(sext_ln170_fu_1905_p1) + $signed(sext_ln170_9_fu_2001_p1));

assign add_ln700_8_fu_2143_p2 = ($signed(sext_ln170_1_fu_1921_p1) + $signed(sext_ln170_2_fu_1937_p1));

assign add_ln700_9_fu_2153_p2 = ($signed(sext_ln700_6_fu_2139_p1) + $signed(sext_ln700_7_fu_2149_p1));

assign add_ln700_fu_2085_p2 = ($signed(sext_ln700_fu_2065_p1) + $signed(select_ln271_3_fu_1886_p3));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((in_V_V_TVALID == 1'b0) & (ap_predicate_op40_read_state2 == 1'b1)) | ((weight_V_V_TVALID == 1'b0) & (icmp_ln248_fu_592_p2 == 1'd0))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state4_io)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (((in_V_V_TVALID == 1'b0) & (ap_predicate_op40_read_state2 == 1'b1)) | ((weight_V_V_TVALID == 1'b0) & (icmp_ln248_fu_592_p2 == 1'd0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state4_io)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (((in_V_V_TVALID == 1'b0) & (ap_predicate_op40_read_state2 == 1'b1)) | ((weight_V_V_TVALID == 1'b0) & (icmp_ln248_fu_592_p2 == 1'd0)))));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = (((in_V_V_TVALID == 1'b0) & (ap_predicate_op40_read_state2 == 1'b1)) | ((weight_V_V_TVALID == 1'b0) & (icmp_ln248_fu_592_p2 == 1'd0)));
end

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_io = ((out_V_V_TREADY == 1'b0) & (icmp_ln289_reg_3835_pp0_iter1_reg == 1'd1));
end

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_act_m_val_V_reg_572 = 'bx;

always @ (*) begin
    ap_predicate_op40_read_state2 = ((icmp_ln252_fu_607_p2 == 1'd1) & (icmp_ln248_fu_592_p2 == 1'd0));
end

assign arg_V_read_assign_14_fu_1112_p4 = {{ap_phi_mux_act_m_val_V_phi_fu_575_p4[31:30]}};

assign arg_V_read_assign_3_fu_938_p4 = {{ap_phi_mux_act_m_val_V_phi_fu_575_p4[7:6]}};

assign arg_V_read_assign_4_fu_966_p4 = {{ap_phi_mux_act_m_val_V_phi_fu_575_p4[9:8]}};

assign arg_V_read_assign_5_fu_994_p4 = {{ap_phi_mux_act_m_val_V_phi_fu_575_p4[11:10]}};

assign i_fu_598_p2 = (i_0_reg_561 + 7'd1);

assign icmp_ln248_fu_592_p2 = ((i_0_reg_561 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln252_fu_607_p2 = ((ap_sig_allocacmp_nf_assign_load_1 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln271_fu_754_p2 = ((sf_1_fu_362 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln289_fu_1842_p2 = ((sf_fu_1836_p2 == 32'd4) ? 1'b1 : 1'b0);

assign icmp_ln301_fu_3002_p2 = ((nf_fu_2996_p2 == 32'd16) ? 1'b1 : 1'b0);

assign icmp_ln321_1_fu_657_p2 = ((trunc_ln321_fu_647_p1 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln321_2_fu_663_p2 = ((trunc_ln321_fu_647_p1 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln321_fu_651_p2 = ((trunc_ln321_fu_647_p1 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln899_10_fu_3349_p2 = (($signed(accu_0_3_V_fu_3083_p2) < $signed(zext_ln186_11_fu_3345_p1)) ? 1'b1 : 1'b0);

assign icmp_ln899_11_fu_3369_p2 = (($signed(accu_0_3_V_fu_3083_p2) < $signed(zext_ln186_12_fu_3365_p1)) ? 1'b1 : 1'b0);

assign icmp_ln899_1_fu_3133_p2 = (($signed(accu_0_0_V_fu_3032_p2) < $signed(zext_ln186_2_fu_3129_p1)) ? 1'b1 : 1'b0);

assign icmp_ln899_2_fu_3153_p2 = (($signed(accu_0_0_V_fu_3032_p2) < $signed(zext_ln186_3_fu_3149_p1)) ? 1'b1 : 1'b0);

assign icmp_ln899_3_fu_3185_p2 = (($signed(accu_0_1_V_fu_3049_p2) < $signed(zext_ln186_4_fu_3181_p1)) ? 1'b1 : 1'b0);

assign icmp_ln899_4_fu_3205_p2 = (($signed(accu_0_1_V_fu_3049_p2) < $signed(zext_ln186_5_fu_3201_p1)) ? 1'b1 : 1'b0);

assign icmp_ln899_5_fu_3225_p2 = (($signed(accu_0_1_V_fu_3049_p2) < $signed(zext_ln186_6_fu_3221_p1)) ? 1'b1 : 1'b0);

assign icmp_ln899_6_fu_3257_p2 = (($signed(accu_0_2_V_fu_3066_p2) < $signed(zext_ln186_7_fu_3253_p1)) ? 1'b1 : 1'b0);

assign icmp_ln899_7_fu_3277_p2 = (($signed(accu_0_2_V_fu_3066_p2) < $signed(zext_ln186_8_fu_3273_p1)) ? 1'b1 : 1'b0);

assign icmp_ln899_8_fu_3297_p2 = (($signed(accu_0_2_V_fu_3066_p2) < $signed(zext_ln186_9_fu_3293_p1)) ? 1'b1 : 1'b0);

assign icmp_ln899_9_fu_3329_p2 = (($signed(accu_0_3_V_fu_3083_p2) < $signed(zext_ln186_10_fu_3325_p1)) ? 1'b1 : 1'b0);

assign icmp_ln899_fu_3113_p2 = (($signed(accu_0_0_V_fu_3032_p2) < $signed(zext_ln186_1_fu_3109_p1)) ? 1'b1 : 1'b0);

assign inElem_V_fu_632_p5 = sf_1_fu_362[1:0];

assign inputBuf_3_V_6_fu_699_p3 = ((or_ln321_fu_669_p2[0:0] === 1'b1) ? inputBuf_3_V_3_fu_378 : select_ln321_2_fu_691_p3);

assign inputBuf_3_V_7_fu_707_p3 = ((icmp_ln321_1_fu_657_p2[0:0] === 1'b1) ? in_V_V_TDATA : inputBuf_3_V_2_fu_374);

assign inputBuf_3_V_8_fu_715_p3 = ((icmp_ln321_2_fu_663_p2[0:0] === 1'b1) ? inputBuf_3_V_2_fu_374 : inputBuf_3_V_7_fu_707_p3);

assign inputBuf_3_V_9_fu_723_p3 = ((icmp_ln321_2_fu_663_p2[0:0] === 1'b1) ? in_V_V_TDATA : inputBuf_3_V_1_fu_370);

assign inputBuf_3_V_fu_683_p3 = ((or_ln321_fu_669_p2[0:0] === 1'b1) ? inputBuf_3_V_4_fu_382 : select_ln321_fu_675_p3);

assign mul_ln1352_10_fu_2011_p0 = zext_ln215_10_fu_2008_p1;

assign mul_ln1352_11_fu_2027_p0 = zext_ln215_11_fu_2024_p1;

assign mul_ln1352_12_fu_2043_p0 = zext_ln215_12_fu_2040_p1;

assign mul_ln1352_13_fu_2059_p0 = zext_ln215_13_fu_2056_p1;

assign mul_ln1352_14_fu_2075_p0 = zext_ln215_14_fu_2072_p1;

assign mul_ln1352_15_fu_1130_p0 = zext_ln215_15_fu_1126_p1;

assign mul_ln1352_16_fu_2194_p0 = zext_ln215_fu_1896_p1;

assign mul_ln1352_17_fu_2207_p0 = zext_ln215_1_fu_1912_p1;

assign mul_ln1352_18_fu_2220_p0 = zext_ln215_2_fu_1928_p1;

assign mul_ln1352_19_fu_1316_p0 = zext_ln215_3_fu_952_p1;

assign mul_ln1352_1_fu_1915_p0 = zext_ln215_1_fu_1912_p1;

assign mul_ln1352_20_fu_1330_p0 = zext_ln215_4_fu_980_p1;

assign mul_ln1352_21_fu_1344_p0 = zext_ln215_5_fu_1008_p1;

assign mul_ln1352_22_fu_2233_p0 = zext_ln215_6_fu_1944_p1;

assign mul_ln1352_23_fu_2246_p0 = zext_ln215_7_fu_1960_p1;

assign mul_ln1352_24_fu_2259_p0 = zext_ln215_8_fu_1976_p1;

assign mul_ln1352_25_fu_2272_p0 = zext_ln215_9_fu_1992_p1;

assign mul_ln1352_26_fu_2285_p0 = zext_ln215_10_fu_2008_p1;

assign mul_ln1352_27_fu_2298_p0 = zext_ln215_11_fu_2024_p1;

assign mul_ln1352_28_fu_2311_p0 = zext_ln215_12_fu_2040_p1;

assign mul_ln1352_29_fu_2324_p0 = zext_ln215_13_fu_2056_p1;

assign mul_ln1352_2_fu_1931_p0 = zext_ln215_2_fu_1928_p1;

assign mul_ln1352_30_fu_2337_p0 = zext_ln215_14_fu_2072_p1;

assign mul_ln1352_31_fu_1358_p0 = zext_ln215_15_fu_1126_p1;

assign mul_ln1352_32_fu_2456_p0 = zext_ln215_fu_1896_p1;

assign mul_ln1352_33_fu_2469_p0 = zext_ln215_1_fu_1912_p1;

assign mul_ln1352_34_fu_2482_p0 = zext_ln215_2_fu_1928_p1;

assign mul_ln1352_35_fu_1544_p0 = zext_ln215_3_fu_952_p1;

assign mul_ln1352_36_fu_1558_p0 = zext_ln215_4_fu_980_p1;

assign mul_ln1352_37_fu_1572_p0 = zext_ln215_5_fu_1008_p1;

assign mul_ln1352_38_fu_2495_p0 = zext_ln215_6_fu_1944_p1;

assign mul_ln1352_39_fu_2508_p0 = zext_ln215_7_fu_1960_p1;

assign mul_ln1352_3_fu_956_p0 = zext_ln215_3_fu_952_p1;

assign mul_ln1352_40_fu_2521_p0 = zext_ln215_8_fu_1976_p1;

assign mul_ln1352_41_fu_2534_p0 = zext_ln215_9_fu_1992_p1;

assign mul_ln1352_42_fu_2547_p0 = zext_ln215_10_fu_2008_p1;

assign mul_ln1352_43_fu_2560_p0 = zext_ln215_11_fu_2024_p1;

assign mul_ln1352_44_fu_2573_p0 = zext_ln215_12_fu_2040_p1;

assign mul_ln1352_45_fu_2586_p0 = zext_ln215_13_fu_2056_p1;

assign mul_ln1352_46_fu_2599_p0 = zext_ln215_14_fu_2072_p1;

assign mul_ln1352_47_fu_1586_p0 = zext_ln215_15_fu_1126_p1;

assign mul_ln1352_48_fu_2718_p0 = zext_ln215_fu_1896_p1;

assign mul_ln1352_49_fu_2731_p0 = zext_ln215_1_fu_1912_p1;

assign mul_ln1352_4_fu_984_p0 = zext_ln215_4_fu_980_p1;

assign mul_ln1352_50_fu_2744_p0 = zext_ln215_2_fu_1928_p1;

assign mul_ln1352_51_fu_1772_p0 = zext_ln215_3_fu_952_p1;

assign mul_ln1352_52_fu_1786_p0 = zext_ln215_4_fu_980_p1;

assign mul_ln1352_53_fu_1800_p0 = zext_ln215_5_fu_1008_p1;

assign mul_ln1352_54_fu_2757_p0 = zext_ln215_6_fu_1944_p1;

assign mul_ln1352_55_fu_2770_p0 = zext_ln215_7_fu_1960_p1;

assign mul_ln1352_56_fu_2783_p0 = zext_ln215_8_fu_1976_p1;

assign mul_ln1352_57_fu_2796_p0 = zext_ln215_9_fu_1992_p1;

assign mul_ln1352_58_fu_2809_p0 = zext_ln215_10_fu_2008_p1;

assign mul_ln1352_59_fu_2822_p0 = zext_ln215_11_fu_2024_p1;

assign mul_ln1352_5_fu_1012_p0 = zext_ln215_5_fu_1008_p1;

assign mul_ln1352_60_fu_2835_p0 = zext_ln215_12_fu_2040_p1;

assign mul_ln1352_61_fu_2848_p0 = zext_ln215_13_fu_2056_p1;

assign mul_ln1352_62_fu_2861_p0 = zext_ln215_14_fu_2072_p1;

assign mul_ln1352_63_fu_1814_p0 = zext_ln215_15_fu_1126_p1;

assign mul_ln1352_6_fu_1947_p0 = zext_ln215_6_fu_1944_p1;

assign mul_ln1352_7_fu_1963_p0 = zext_ln215_7_fu_1960_p1;

assign mul_ln1352_8_fu_1979_p0 = zext_ln215_8_fu_1976_p1;

assign mul_ln1352_9_fu_1995_p0 = zext_ln215_9_fu_1992_p1;

assign mul_ln1352_fu_1899_p0 = zext_ln215_fu_1896_p1;

assign nf_fu_2996_p2 = (nf_assign_fu_366 + 32'd1);

assign or_ln321_fu_669_p2 = (icmp_ln321_2_fu_663_p2 | icmp_ln321_1_fu_657_p2);

assign out_V_V_TDATA = {{{{add_ln700_71_fu_3391_p2}, {add_ln700_69_fu_3319_p2}}, {add_ln700_67_fu_3247_p2}}, {add_ln700_65_fu_3175_p2}};

assign select_ln271_1_fu_1872_p3 = ((icmp_ln271_reg_3487[0:0] === 1'b1) ? 9'd0 : ap_sig_allocacmp_accu_V_0_2_0_load);

assign select_ln271_2_fu_1879_p3 = ((icmp_ln271_reg_3487[0:0] === 1'b1) ? 9'd0 : ap_sig_allocacmp_accu_V_0_1_0_load);

assign select_ln271_3_fu_1886_p3 = ((icmp_ln271_reg_3487[0:0] === 1'b1) ? 9'd0 : ap_sig_allocacmp_accu_V_0_0_0_load);

assign select_ln271_fu_1865_p3 = ((icmp_ln271_reg_3487[0:0] === 1'b1) ? 9'd0 : ap_sig_allocacmp_accu_V_0_3_0_load);

assign select_ln301_fu_3008_p3 = ((icmp_ln301_fu_3002_p2[0:0] === 1'b1) ? 32'd0 : nf_fu_2996_p2);

assign select_ln321_2_fu_691_p3 = ((icmp_ln321_fu_651_p2[0:0] === 1'b1) ? in_V_V_TDATA : inputBuf_3_V_3_fu_378);

assign select_ln321_fu_675_p3 = ((icmp_ln321_fu_651_p2[0:0] === 1'b1) ? inputBuf_3_V_4_fu_382 : in_V_V_TDATA);

assign sext_ln170_10_fu_2017_p1 = mul_ln1352_10_fu_2011_p2;

assign sext_ln170_11_fu_2033_p1 = mul_ln1352_11_fu_2027_p2;

assign sext_ln170_12_fu_2049_p1 = mul_ln1352_12_fu_2043_p2;

assign sext_ln170_13_fu_2081_p1 = mul_ln1352_14_fu_2075_p2;

assign sext_ln170_14_fu_2200_p1 = mul_ln1352_16_fu_2194_p2;

assign sext_ln170_15_fu_2213_p1 = mul_ln1352_17_fu_2207_p2;

assign sext_ln170_16_fu_2226_p1 = mul_ln1352_18_fu_2220_p2;

assign sext_ln170_17_fu_1322_p1 = mul_ln1352_19_fu_1316_p2;

assign sext_ln170_18_fu_1336_p1 = mul_ln1352_20_fu_1330_p2;

assign sext_ln170_19_fu_1350_p1 = mul_ln1352_21_fu_1344_p2;

assign sext_ln170_1_fu_1921_p1 = mul_ln1352_1_fu_1915_p2;

assign sext_ln170_20_fu_2239_p1 = mul_ln1352_22_fu_2233_p2;

assign sext_ln170_21_fu_2252_p1 = mul_ln1352_23_fu_2246_p2;

assign sext_ln170_22_fu_2265_p1 = mul_ln1352_24_fu_2259_p2;

assign sext_ln170_23_fu_2278_p1 = mul_ln1352_25_fu_2272_p2;

assign sext_ln170_24_fu_2291_p1 = mul_ln1352_26_fu_2285_p2;

assign sext_ln170_25_fu_2304_p1 = mul_ln1352_27_fu_2298_p2;

assign sext_ln170_26_fu_2317_p1 = mul_ln1352_28_fu_2311_p2;

assign sext_ln170_27_fu_2343_p1 = mul_ln1352_30_fu_2337_p2;

assign sext_ln170_28_fu_2462_p1 = mul_ln1352_32_fu_2456_p2;

assign sext_ln170_29_fu_2475_p1 = mul_ln1352_33_fu_2469_p2;

assign sext_ln170_2_fu_1937_p1 = mul_ln1352_2_fu_1931_p2;

assign sext_ln170_30_fu_2488_p1 = mul_ln1352_34_fu_2482_p2;

assign sext_ln170_31_fu_1550_p1 = mul_ln1352_35_fu_1544_p2;

assign sext_ln170_32_fu_1564_p1 = mul_ln1352_36_fu_1558_p2;

assign sext_ln170_33_fu_1578_p1 = mul_ln1352_37_fu_1572_p2;

assign sext_ln170_34_fu_2501_p1 = mul_ln1352_38_fu_2495_p2;

assign sext_ln170_35_fu_2514_p1 = mul_ln1352_39_fu_2508_p2;

assign sext_ln170_36_fu_2527_p1 = mul_ln1352_40_fu_2521_p2;

assign sext_ln170_37_fu_2540_p1 = mul_ln1352_41_fu_2534_p2;

assign sext_ln170_38_fu_2553_p1 = mul_ln1352_42_fu_2547_p2;

assign sext_ln170_39_fu_2566_p1 = mul_ln1352_43_fu_2560_p2;

assign sext_ln170_3_fu_962_p1 = mul_ln1352_3_fu_956_p2;

assign sext_ln170_40_fu_2579_p1 = mul_ln1352_44_fu_2573_p2;

assign sext_ln170_41_fu_2605_p1 = mul_ln1352_46_fu_2599_p2;

assign sext_ln170_42_fu_2724_p1 = mul_ln1352_48_fu_2718_p2;

assign sext_ln170_43_fu_2737_p1 = mul_ln1352_49_fu_2731_p2;

assign sext_ln170_44_fu_2750_p1 = mul_ln1352_50_fu_2744_p2;

assign sext_ln170_45_fu_1778_p1 = mul_ln1352_51_fu_1772_p2;

assign sext_ln170_46_fu_1792_p1 = mul_ln1352_52_fu_1786_p2;

assign sext_ln170_47_fu_1806_p1 = mul_ln1352_53_fu_1800_p2;

assign sext_ln170_48_fu_2763_p1 = mul_ln1352_54_fu_2757_p2;

assign sext_ln170_49_fu_2776_p1 = mul_ln1352_55_fu_2770_p2;

assign sext_ln170_4_fu_990_p1 = mul_ln1352_4_fu_984_p2;

assign sext_ln170_50_fu_2789_p1 = mul_ln1352_56_fu_2783_p2;

assign sext_ln170_51_fu_2802_p1 = mul_ln1352_57_fu_2796_p2;

assign sext_ln170_52_fu_2815_p1 = mul_ln1352_58_fu_2809_p2;

assign sext_ln170_53_fu_2828_p1 = mul_ln1352_59_fu_2822_p2;

assign sext_ln170_54_fu_2841_p1 = mul_ln1352_60_fu_2835_p2;

assign sext_ln170_55_fu_2867_p1 = mul_ln1352_62_fu_2861_p2;

assign sext_ln170_5_fu_1018_p1 = mul_ln1352_5_fu_1012_p2;

assign sext_ln170_6_fu_1953_p1 = mul_ln1352_6_fu_1947_p2;

assign sext_ln170_7_fu_1969_p1 = mul_ln1352_7_fu_1963_p2;

assign sext_ln170_8_fu_1985_p1 = mul_ln1352_8_fu_1979_p2;

assign sext_ln170_9_fu_2001_p1 = mul_ln1352_9_fu_1995_p2;

assign sext_ln170_fu_1905_p1 = mul_ln1352_fu_1899_p2;

assign sext_ln700_10_fu_2166_p1 = $signed(add_ln700_11_reg_3620);

assign sext_ln700_11_fu_2181_p1 = $signed(add_ln700_13_fu_2175_p2);

assign sext_ln700_12_fu_3029_p1 = $signed(add_ln700_14_reg_3849);

assign sext_ln700_13_fu_2330_p1 = mul_ln1352_29_fu_2324_p2;

assign sext_ln700_14_fu_1364_p1 = mul_ln1352_31_fu_1358_p2;

assign sext_ln700_15_fu_2359_p1 = $signed(add_ln700_17_fu_2353_p2);

assign sext_ln700_16_fu_2375_p1 = $signed(add_ln700_19_fu_2369_p2);

assign sext_ln700_17_fu_2385_p1 = $signed(add_ln700_20_fu_2379_p2);

assign sext_ln700_18_fu_3038_p1 = $signed(add_ln700_21_reg_3859);

assign sext_ln700_19_fu_2401_p1 = $signed(add_ln700_23_fu_2395_p2);

assign sext_ln700_1_fu_1136_p1 = mul_ln1352_15_fu_1130_p2;

assign sext_ln700_20_fu_2411_p1 = $signed(add_ln700_24_fu_2405_p2);

assign sext_ln700_21_fu_2421_p1 = $signed(add_ln700_25_fu_2415_p2);

assign sext_ln700_22_fu_2425_p1 = $signed(add_ln700_26_reg_3685);

assign sext_ln700_23_fu_2428_p1 = $signed(add_ln700_27_reg_3690);

assign sext_ln700_24_fu_2443_p1 = $signed(add_ln700_29_fu_2437_p2);

assign sext_ln700_25_fu_3046_p1 = $signed(add_ln700_30_reg_3864);

assign sext_ln700_26_fu_2592_p1 = mul_ln1352_45_fu_2586_p2;

assign sext_ln700_27_fu_1592_p1 = mul_ln1352_47_fu_1586_p2;

assign sext_ln700_28_fu_2621_p1 = $signed(add_ln700_33_fu_2615_p2);

assign sext_ln700_29_fu_2637_p1 = $signed(add_ln700_35_fu_2631_p2);

assign sext_ln700_2_fu_2097_p1 = $signed(add_ln700_1_fu_2091_p2);

assign sext_ln700_30_fu_2647_p1 = $signed(add_ln700_36_fu_2641_p2);

assign sext_ln700_31_fu_3055_p1 = $signed(add_ln700_37_reg_3874);

assign sext_ln700_32_fu_2663_p1 = $signed(add_ln700_39_fu_2657_p2);

assign sext_ln700_33_fu_2673_p1 = $signed(add_ln700_40_fu_2667_p2);

assign sext_ln700_34_fu_2683_p1 = $signed(add_ln700_41_fu_2677_p2);

assign sext_ln700_35_fu_2687_p1 = $signed(add_ln700_42_reg_3755);

assign sext_ln700_36_fu_2690_p1 = $signed(add_ln700_43_reg_3760);

assign sext_ln700_37_fu_2705_p1 = $signed(add_ln700_45_fu_2699_p2);

assign sext_ln700_38_fu_3063_p1 = $signed(add_ln700_46_reg_3879);

assign sext_ln700_39_fu_2854_p1 = mul_ln1352_61_fu_2848_p2;

assign sext_ln700_3_fu_2113_p1 = $signed(add_ln700_3_fu_2107_p2);

assign sext_ln700_40_fu_1820_p1 = mul_ln1352_63_fu_1814_p2;

assign sext_ln700_41_fu_2883_p1 = $signed(add_ln700_49_fu_2877_p2);

assign sext_ln700_42_fu_2899_p1 = $signed(add_ln700_51_fu_2893_p2);

assign sext_ln700_43_fu_2909_p1 = $signed(add_ln700_52_fu_2903_p2);

assign sext_ln700_44_fu_3072_p1 = $signed(add_ln700_53_reg_3889);

assign sext_ln700_45_fu_2925_p1 = $signed(add_ln700_55_fu_2919_p2);

assign sext_ln700_46_fu_2935_p1 = $signed(add_ln700_56_fu_2929_p2);

assign sext_ln700_47_fu_2945_p1 = $signed(add_ln700_57_fu_2939_p2);

assign sext_ln700_48_fu_2949_p1 = $signed(add_ln700_58_reg_3825);

assign sext_ln700_49_fu_2952_p1 = $signed(add_ln700_59_reg_3830);

assign sext_ln700_4_fu_2123_p1 = $signed(add_ln700_4_fu_2117_p2);

assign sext_ln700_50_fu_2967_p1 = $signed(add_ln700_61_fu_2961_p2);

assign sext_ln700_51_fu_3080_p1 = $signed(add_ln700_62_reg_3894);

assign sext_ln700_5_fu_3021_p1 = $signed(add_ln700_5_reg_3844);

assign sext_ln700_6_fu_2139_p1 = $signed(add_ln700_7_fu_2133_p2);

assign sext_ln700_7_fu_2149_p1 = $signed(add_ln700_8_fu_2143_p2);

assign sext_ln700_8_fu_2159_p1 = $signed(add_ln700_9_fu_2153_p2);

assign sext_ln700_9_fu_2163_p1 = $signed(add_ln700_10_reg_3615);

assign sext_ln700_fu_2065_p1 = mul_ln1352_13_fu_2059_p2;

assign sf_fu_1836_p2 = (32'd1 + sf_1_fu_362);

assign threshs_m_thresholds_10_address0 = zext_ln186_fu_2980_p1;

assign threshs_m_thresholds_11_address0 = zext_ln186_fu_2980_p1;

assign threshs_m_thresholds_1_address0 = zext_ln186_fu_2980_p1;

assign threshs_m_thresholds_2_address0 = zext_ln186_fu_2980_p1;

assign threshs_m_thresholds_3_address0 = zext_ln186_fu_2980_p1;

assign threshs_m_thresholds_4_address0 = zext_ln186_fu_2980_p1;

assign threshs_m_thresholds_5_address0 = zext_ln186_fu_2980_p1;

assign threshs_m_thresholds_6_address0 = zext_ln186_fu_2980_p1;

assign threshs_m_thresholds_7_address0 = zext_ln186_fu_2980_p1;

assign threshs_m_thresholds_8_address0 = zext_ln186_fu_2980_p1;

assign threshs_m_thresholds_9_address0 = zext_ln186_fu_2980_p1;

assign threshs_m_thresholds_address0 = zext_ln186_fu_2980_p1;

assign trunc_ln321_fu_647_p1 = sf_1_fu_362[1:0];

assign trunc_ln647_fu_914_p1 = ap_phi_mux_act_m_val_V_phi_fu_575_p4[1:0];

assign wgt_M_instance_0_V_fu_760_p1 = weight_V_V_TDATA[1:0];

assign wgt_M_instance_15_1_fu_1302_p4 = {{weight_V_V_TDATA[63:62]}};

assign wgt_M_instance_15_2_fu_1530_p4 = {{weight_V_V_TDATA[95:94]}};

assign wgt_M_instance_15_3_fu_1758_p4 = {{weight_V_V_TDATA[127:126]}};

assign wgt_M_instance_15_s_fu_904_p4 = {{weight_V_V_TDATA[31:30]}};

assign wgt_M_instance_3_V_1_fu_1182_p4 = {{weight_V_V_TDATA[39:38]}};

assign wgt_M_instance_3_V_2_fu_1410_p4 = {{weight_V_V_TDATA[71:70]}};

assign wgt_M_instance_3_V_3_fu_1638_p4 = {{weight_V_V_TDATA[103:102]}};

assign wgt_M_instance_3_V_fu_784_p4 = {{weight_V_V_TDATA[7:6]}};

assign wgt_M_instance_4_V_1_fu_1192_p4 = {{weight_V_V_TDATA[41:40]}};

assign wgt_M_instance_4_V_2_fu_1420_p4 = {{weight_V_V_TDATA[73:72]}};

assign wgt_M_instance_4_V_3_fu_1648_p4 = {{weight_V_V_TDATA[105:104]}};

assign wgt_M_instance_4_V_fu_794_p4 = {{weight_V_V_TDATA[9:8]}};

assign wgt_M_instance_5_V_1_fu_1202_p4 = {{weight_V_V_TDATA[43:42]}};

assign wgt_M_instance_5_V_2_fu_1430_p4 = {{weight_V_V_TDATA[75:74]}};

assign wgt_M_instance_5_V_3_fu_1658_p4 = {{weight_V_V_TDATA[107:106]}};

assign wgt_M_instance_5_V_fu_804_p4 = {{weight_V_V_TDATA[11:10]}};

assign xor_ln899_10_fu_3355_p2 = (icmp_ln899_10_fu_3349_p2 ^ 1'd1);

assign xor_ln899_11_fu_3375_p2 = (icmp_ln899_11_fu_3369_p2 ^ 1'd1);

assign xor_ln899_1_fu_3139_p2 = (icmp_ln899_1_fu_3133_p2 ^ 1'd1);

assign xor_ln899_2_fu_3159_p2 = (icmp_ln899_2_fu_3153_p2 ^ 1'd1);

assign xor_ln899_3_fu_3191_p2 = (icmp_ln899_3_fu_3185_p2 ^ 1'd1);

assign xor_ln899_4_fu_3211_p2 = (icmp_ln899_4_fu_3205_p2 ^ 1'd1);

assign xor_ln899_5_fu_3231_p2 = (icmp_ln899_5_fu_3225_p2 ^ 1'd1);

assign xor_ln899_6_fu_3263_p2 = (icmp_ln899_6_fu_3257_p2 ^ 1'd1);

assign xor_ln899_7_fu_3283_p2 = (icmp_ln899_7_fu_3277_p2 ^ 1'd1);

assign xor_ln899_8_fu_3303_p2 = (icmp_ln899_8_fu_3297_p2 ^ 1'd1);

assign xor_ln899_9_fu_3335_p2 = (icmp_ln899_9_fu_3329_p2 ^ 1'd1);

assign xor_ln899_fu_3119_p2 = (icmp_ln899_fu_3113_p2 ^ 1'd1);

assign zext_ln186_10_fu_3325_p1 = threshs_m_thresholds_2_q0;

assign zext_ln186_11_fu_3345_p1 = threshs_m_thresholds_1_q0;

assign zext_ln186_12_fu_3365_p1 = threshs_m_thresholds_q0;

assign zext_ln186_1_fu_3109_p1 = threshs_m_thresholds_11_q0;

assign zext_ln186_2_fu_3129_p1 = threshs_m_thresholds_10_q0;

assign zext_ln186_3_fu_3149_p1 = threshs_m_thresholds_9_q0;

assign zext_ln186_4_fu_3181_p1 = threshs_m_thresholds_8_q0;

assign zext_ln186_5_fu_3201_p1 = threshs_m_thresholds_7_q0;

assign zext_ln186_6_fu_3221_p1 = threshs_m_thresholds_6_q0;

assign zext_ln186_7_fu_3253_p1 = threshs_m_thresholds_5_q0;

assign zext_ln186_8_fu_3273_p1 = threshs_m_thresholds_4_q0;

assign zext_ln186_9_fu_3293_p1 = threshs_m_thresholds_3_q0;

assign zext_ln186_fu_2980_p1 = nf_assign_fu_366;

assign zext_ln215_10_fu_2008_p1 = arg_V_read_assign_s_reg_3590;

assign zext_ln215_11_fu_2024_p1 = arg_V_read_assign_10_reg_3595;

assign zext_ln215_12_fu_2040_p1 = arg_V_read_assign_11_reg_3600;

assign zext_ln215_13_fu_2056_p1 = arg_V_read_assign_12_reg_3605;

assign zext_ln215_14_fu_2072_p1 = arg_V_read_assign_13_reg_3610;

assign zext_ln215_15_fu_1126_p1 = arg_V_read_assign_14_fu_1112_p4;

assign zext_ln215_1_fu_1912_p1 = arg_V_read_assign_1_reg_3560;

assign zext_ln215_2_fu_1928_p1 = arg_V_read_assign_2_reg_3565;

assign zext_ln215_3_fu_952_p1 = arg_V_read_assign_3_fu_938_p4;

assign zext_ln215_4_fu_980_p1 = arg_V_read_assign_4_fu_966_p4;

assign zext_ln215_5_fu_1008_p1 = arg_V_read_assign_5_fu_994_p4;

assign zext_ln215_6_fu_1944_p1 = arg_V_read_assign_6_reg_3570;

assign zext_ln215_7_fu_1960_p1 = arg_V_read_assign_7_reg_3575;

assign zext_ln215_8_fu_1976_p1 = arg_V_read_assign_8_reg_3580;

assign zext_ln215_9_fu_1992_p1 = arg_V_read_assign_9_reg_3585;

assign zext_ln215_fu_1896_p1 = trunc_ln647_reg_3555;

assign zext_ln700_10_fu_3361_p1 = xor_ln899_10_fu_3355_p2;

assign zext_ln700_11_fu_3381_p1 = xor_ln899_11_fu_3375_p2;

assign zext_ln700_1_fu_3145_p1 = xor_ln899_1_fu_3139_p2;

assign zext_ln700_2_fu_3165_p1 = xor_ln899_2_fu_3159_p2;

assign zext_ln700_3_fu_3197_p1 = xor_ln899_3_fu_3191_p2;

assign zext_ln700_4_fu_3217_p1 = xor_ln899_4_fu_3211_p2;

assign zext_ln700_5_fu_3237_p1 = xor_ln899_5_fu_3231_p2;

assign zext_ln700_6_fu_3269_p1 = xor_ln899_6_fu_3263_p2;

assign zext_ln700_7_fu_3289_p1 = xor_ln899_7_fu_3283_p2;

assign zext_ln700_8_fu_3309_p1 = xor_ln899_8_fu_3303_p2;

assign zext_ln700_9_fu_3341_p1 = xor_ln899_9_fu_3335_p2;

assign zext_ln700_fu_3125_p1 = xor_ln899_fu_3119_p2;

endmodule //StreamingFCLayer_Batch_1_Matrix_Vector_Activa
