#!/bin/bash 
cd /tmp/finn_dev_uma/code_gen_ipgen_StreamingDataflowPartition_2_IODMA_0_01shf2du
vivado_hls /tmp/finn_dev_uma/code_gen_ipgen_StreamingDataflowPartition_2_IODMA_0_01shf2du/hls_syn_StreamingDataflowPartition_2_IODMA_0.tcl
cd /workspace/finn/notebooks/end2end_example/cybersecurity
