# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /tmp/finn_dev_uma/vivado_stitch_proj_x6mie7gk/finn_vivado_stitch_proj.srcs/sources_1/bd/StreamingDataflowPartition_0/ip/StreamingDataflowPartition_0_StreamingDataflowPartition_0_IODMA_0_0/StreamingDataflowPartition_0_StreamingDataflowPartition_0_IODMA_0_0.xci
# IP: The module: 'StreamingDataflowPartition_0_StreamingDataflowPartition_0_IODMA_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /tmp/finn_dev_uma/vivado_stitch_proj_x6mie7gk/finn_vivado_stitch_proj.srcs/sources_1/bd/StreamingDataflowPartition_0/ip/StreamingDataflowPartition_0_StreamingDataflowPartition_0_IODMA_0_0/constraints/StreamingDataflowPartition_0_IODMA_0_StreamingDataflowPartition_0_IODMA_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'StreamingDataflowPartition_0_StreamingDataflowPartition_0_IODMA_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /tmp/finn_dev_uma/vivado_stitch_proj_x6mie7gk/finn_vivado_stitch_proj.srcs/sources_1/bd/StreamingDataflowPartition_0/ip/StreamingDataflowPartition_0_StreamingDataflowPartition_0_IODMA_0_0/StreamingDataflowPartition_0_StreamingDataflowPartition_0_IODMA_0_0.xci
# IP: The module: 'StreamingDataflowPartition_0_StreamingDataflowPartition_0_IODMA_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /tmp/finn_dev_uma/vivado_stitch_proj_x6mie7gk/finn_vivado_stitch_proj.srcs/sources_1/bd/StreamingDataflowPartition_0/ip/StreamingDataflowPartition_0_StreamingDataflowPartition_0_IODMA_0_0/constraints/StreamingDataflowPartition_0_IODMA_0_StreamingDataflowPartition_0_IODMA_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'StreamingDataflowPartition_0_StreamingDataflowPartition_0_IODMA_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
