# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /tmp/finn_dev_uma/vivado_zynq_proj_89uua1b8/finn_zynq_link.srcs/sources_1/bd/top/ip/top_zynq_ps_0/top_zynq_ps_0.xci
# IP: The module: 'top_zynq_ps_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /tmp/finn_dev_uma/vivado_zynq_proj_89uua1b8/finn_zynq_link.srcs/sources_1/bd/top/ip/top_zynq_ps_0/top_zynq_ps_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_zynq_ps_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /tmp/finn_dev_uma/vivado_zynq_proj_89uua1b8/finn_zynq_link.srcs/sources_1/bd/top/ip/top_zynq_ps_0/top_zynq_ps_0.xci
# IP: The module: 'top_zynq_ps_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /tmp/finn_dev_uma/vivado_zynq_proj_89uua1b8/finn_zynq_link.srcs/sources_1/bd/top/ip/top_zynq_ps_0/top_zynq_ps_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_zynq_ps_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
