// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "StreamingDataflowPartition_0_IODMA_0_Mem2Stream.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic StreamingDataflowPartition_0_IODMA_0_Mem2Stream::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic StreamingDataflowPartition_0_IODMA_0_Mem2Stream::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<10> StreamingDataflowPartition_0_IODMA_0_Mem2Stream::ap_ST_fsm_state1 = "1";
const sc_lv<10> StreamingDataflowPartition_0_IODMA_0_Mem2Stream::ap_ST_fsm_state2 = "10";
const sc_lv<10> StreamingDataflowPartition_0_IODMA_0_Mem2Stream::ap_ST_fsm_state3 = "100";
const sc_lv<10> StreamingDataflowPartition_0_IODMA_0_Mem2Stream::ap_ST_fsm_state4 = "1000";
const sc_lv<10> StreamingDataflowPartition_0_IODMA_0_Mem2Stream::ap_ST_fsm_state5 = "10000";
const sc_lv<10> StreamingDataflowPartition_0_IODMA_0_Mem2Stream::ap_ST_fsm_state6 = "100000";
const sc_lv<10> StreamingDataflowPartition_0_IODMA_0_Mem2Stream::ap_ST_fsm_state7 = "1000000";
const sc_lv<10> StreamingDataflowPartition_0_IODMA_0_Mem2Stream::ap_ST_fsm_state8 = "10000000";
const sc_lv<10> StreamingDataflowPartition_0_IODMA_0_Mem2Stream::ap_ST_fsm_pp0_stage0 = "100000000";
const sc_lv<10> StreamingDataflowPartition_0_IODMA_0_Mem2Stream::ap_ST_fsm_state11 = "1000000000";
const bool StreamingDataflowPartition_0_IODMA_0_Mem2Stream::ap_const_boolean_1 = true;
const sc_lv<32> StreamingDataflowPartition_0_IODMA_0_Mem2Stream::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<64> StreamingDataflowPartition_0_IODMA_0_Mem2Stream::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<1> StreamingDataflowPartition_0_IODMA_0_Mem2Stream::ap_const_lv1_0 = "0";
const sc_lv<3> StreamingDataflowPartition_0_IODMA_0_Mem2Stream::ap_const_lv3_0 = "000";
const sc_lv<2> StreamingDataflowPartition_0_IODMA_0_Mem2Stream::ap_const_lv2_0 = "00";
const sc_lv<4> StreamingDataflowPartition_0_IODMA_0_Mem2Stream::ap_const_lv4_0 = "0000";
const sc_lv<16> StreamingDataflowPartition_0_IODMA_0_Mem2Stream::ap_const_lv16_0 = "0000000000000000";
const sc_lv<32> StreamingDataflowPartition_0_IODMA_0_Mem2Stream::ap_const_lv32_1 = "1";
const sc_lv<32> StreamingDataflowPartition_0_IODMA_0_Mem2Stream::ap_const_lv32_8 = "1000";
const bool StreamingDataflowPartition_0_IODMA_0_Mem2Stream::ap_const_boolean_0 = false;
const sc_lv<32> StreamingDataflowPartition_0_IODMA_0_Mem2Stream::ap_const_lv32_7 = "111";
const sc_lv<1> StreamingDataflowPartition_0_IODMA_0_Mem2Stream::ap_const_lv1_1 = "1";
const sc_lv<10> StreamingDataflowPartition_0_IODMA_0_Mem2Stream::ap_const_lv10_0 = "0000000000";
const sc_lv<32> StreamingDataflowPartition_0_IODMA_0_Mem2Stream::ap_const_lv32_280 = "1010000000";
const sc_lv<10> StreamingDataflowPartition_0_IODMA_0_Mem2Stream::ap_const_lv10_280 = "1010000000";
const sc_lv<10> StreamingDataflowPartition_0_IODMA_0_Mem2Stream::ap_const_lv10_1 = "1";
const sc_lv<32> StreamingDataflowPartition_0_IODMA_0_Mem2Stream::ap_const_lv32_9 = "1001";

StreamingDataflowPartition_0_IODMA_0_Mem2Stream::StreamingDataflowPartition_0_IODMA_0_Mem2Stream(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln142_fu_109_p2);
    sensitive << ( zext_ln142_fu_105_p1 );
    sensitive << ( in_V_offset_cast_fu_101_p1 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( m_axi_in_V_RVALID );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln140_reg_139 );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( m_axi_in_V_RVALID );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln140_reg_139 );
    sensitive << ( ap_block_state10_io );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( m_axi_in_V_RVALID );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln140_reg_139 );
    sensitive << ( ap_block_state10_io );

    SC_METHOD(thread_ap_block_state10_io);
    sensitive << ( out_V_V_TREADY );
    sensitive << ( icmp_ln140_reg_139 );

    SC_METHOD(thread_ap_block_state10_pp0_stage0_iter1);
    sensitive << ( m_axi_in_V_RVALID );
    sensitive << ( icmp_ln140_reg_139 );

    SC_METHOD(thread_ap_block_state9_pp0_stage0_iter0);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state9);
    sensitive << ( icmp_ln140_fu_121_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_i_fu_127_p2);
    sensitive << ( i_0_reg_90 );

    SC_METHOD(thread_icmp_ln140_fu_121_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( i_0_reg_90 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_in_V_blk_n_AR);
    sensitive << ( m_axi_in_V_ARREADY );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_in_V_blk_n_R);
    sensitive << ( m_axi_in_V_RVALID );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln140_reg_139 );

    SC_METHOD(thread_in_V_offset_cast_fu_101_p1);
    sensitive << ( in_V_offset );

    SC_METHOD(thread_m_axi_in_V_ARADDR);
    sensitive << ( m_axi_in_V_ARREADY );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( in_V_addr_reg_133 );

    SC_METHOD(thread_m_axi_in_V_ARBURST);

    SC_METHOD(thread_m_axi_in_V_ARCACHE);

    SC_METHOD(thread_m_axi_in_V_ARID);

    SC_METHOD(thread_m_axi_in_V_ARLEN);
    sensitive << ( m_axi_in_V_ARREADY );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_m_axi_in_V_ARLOCK);

    SC_METHOD(thread_m_axi_in_V_ARPROT);

    SC_METHOD(thread_m_axi_in_V_ARQOS);

    SC_METHOD(thread_m_axi_in_V_ARREGION);

    SC_METHOD(thread_m_axi_in_V_ARSIZE);

    SC_METHOD(thread_m_axi_in_V_ARUSER);

    SC_METHOD(thread_m_axi_in_V_ARVALID);
    sensitive << ( m_axi_in_V_ARREADY );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_m_axi_in_V_AWADDR);

    SC_METHOD(thread_m_axi_in_V_AWBURST);

    SC_METHOD(thread_m_axi_in_V_AWCACHE);

    SC_METHOD(thread_m_axi_in_V_AWID);

    SC_METHOD(thread_m_axi_in_V_AWLEN);

    SC_METHOD(thread_m_axi_in_V_AWLOCK);

    SC_METHOD(thread_m_axi_in_V_AWPROT);

    SC_METHOD(thread_m_axi_in_V_AWQOS);

    SC_METHOD(thread_m_axi_in_V_AWREGION);

    SC_METHOD(thread_m_axi_in_V_AWSIZE);

    SC_METHOD(thread_m_axi_in_V_AWUSER);

    SC_METHOD(thread_m_axi_in_V_AWVALID);

    SC_METHOD(thread_m_axi_in_V_BREADY);

    SC_METHOD(thread_m_axi_in_V_RREADY);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln140_reg_139 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_m_axi_in_V_WDATA);

    SC_METHOD(thread_m_axi_in_V_WID);

    SC_METHOD(thread_m_axi_in_V_WLAST);

    SC_METHOD(thread_m_axi_in_V_WSTRB);

    SC_METHOD(thread_m_axi_in_V_WUSER);

    SC_METHOD(thread_m_axi_in_V_WVALID);

    SC_METHOD(thread_out_V_V_TDATA);
    sensitive << ( m_axi_in_V_RDATA );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln140_reg_139 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_out_V_V_TDATA_blk_n);
    sensitive << ( out_V_V_TREADY );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln140_reg_139 );

    SC_METHOD(thread_out_V_V_TVALID);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln140_reg_139 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_zext_ln142_fu_105_p1);
    sensitive << ( in_V_offset1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( m_axi_in_V_ARREADY );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln140_fu_121_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );

    ap_CS_fsm = "0000000001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "StreamingDataflowPartition_0_IODMA_0_Mem2Stream_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, m_axi_in_V_AWVALID, "(port)m_axi_in_V_AWVALID");
    sc_trace(mVcdFile, m_axi_in_V_AWREADY, "(port)m_axi_in_V_AWREADY");
    sc_trace(mVcdFile, m_axi_in_V_AWADDR, "(port)m_axi_in_V_AWADDR");
    sc_trace(mVcdFile, m_axi_in_V_AWID, "(port)m_axi_in_V_AWID");
    sc_trace(mVcdFile, m_axi_in_V_AWLEN, "(port)m_axi_in_V_AWLEN");
    sc_trace(mVcdFile, m_axi_in_V_AWSIZE, "(port)m_axi_in_V_AWSIZE");
    sc_trace(mVcdFile, m_axi_in_V_AWBURST, "(port)m_axi_in_V_AWBURST");
    sc_trace(mVcdFile, m_axi_in_V_AWLOCK, "(port)m_axi_in_V_AWLOCK");
    sc_trace(mVcdFile, m_axi_in_V_AWCACHE, "(port)m_axi_in_V_AWCACHE");
    sc_trace(mVcdFile, m_axi_in_V_AWPROT, "(port)m_axi_in_V_AWPROT");
    sc_trace(mVcdFile, m_axi_in_V_AWQOS, "(port)m_axi_in_V_AWQOS");
    sc_trace(mVcdFile, m_axi_in_V_AWREGION, "(port)m_axi_in_V_AWREGION");
    sc_trace(mVcdFile, m_axi_in_V_AWUSER, "(port)m_axi_in_V_AWUSER");
    sc_trace(mVcdFile, m_axi_in_V_WVALID, "(port)m_axi_in_V_WVALID");
    sc_trace(mVcdFile, m_axi_in_V_WREADY, "(port)m_axi_in_V_WREADY");
    sc_trace(mVcdFile, m_axi_in_V_WDATA, "(port)m_axi_in_V_WDATA");
    sc_trace(mVcdFile, m_axi_in_V_WSTRB, "(port)m_axi_in_V_WSTRB");
    sc_trace(mVcdFile, m_axi_in_V_WLAST, "(port)m_axi_in_V_WLAST");
    sc_trace(mVcdFile, m_axi_in_V_WID, "(port)m_axi_in_V_WID");
    sc_trace(mVcdFile, m_axi_in_V_WUSER, "(port)m_axi_in_V_WUSER");
    sc_trace(mVcdFile, m_axi_in_V_ARVALID, "(port)m_axi_in_V_ARVALID");
    sc_trace(mVcdFile, m_axi_in_V_ARREADY, "(port)m_axi_in_V_ARREADY");
    sc_trace(mVcdFile, m_axi_in_V_ARADDR, "(port)m_axi_in_V_ARADDR");
    sc_trace(mVcdFile, m_axi_in_V_ARID, "(port)m_axi_in_V_ARID");
    sc_trace(mVcdFile, m_axi_in_V_ARLEN, "(port)m_axi_in_V_ARLEN");
    sc_trace(mVcdFile, m_axi_in_V_ARSIZE, "(port)m_axi_in_V_ARSIZE");
    sc_trace(mVcdFile, m_axi_in_V_ARBURST, "(port)m_axi_in_V_ARBURST");
    sc_trace(mVcdFile, m_axi_in_V_ARLOCK, "(port)m_axi_in_V_ARLOCK");
    sc_trace(mVcdFile, m_axi_in_V_ARCACHE, "(port)m_axi_in_V_ARCACHE");
    sc_trace(mVcdFile, m_axi_in_V_ARPROT, "(port)m_axi_in_V_ARPROT");
    sc_trace(mVcdFile, m_axi_in_V_ARQOS, "(port)m_axi_in_V_ARQOS");
    sc_trace(mVcdFile, m_axi_in_V_ARREGION, "(port)m_axi_in_V_ARREGION");
    sc_trace(mVcdFile, m_axi_in_V_ARUSER, "(port)m_axi_in_V_ARUSER");
    sc_trace(mVcdFile, m_axi_in_V_RVALID, "(port)m_axi_in_V_RVALID");
    sc_trace(mVcdFile, m_axi_in_V_RREADY, "(port)m_axi_in_V_RREADY");
    sc_trace(mVcdFile, m_axi_in_V_RDATA, "(port)m_axi_in_V_RDATA");
    sc_trace(mVcdFile, m_axi_in_V_RLAST, "(port)m_axi_in_V_RLAST");
    sc_trace(mVcdFile, m_axi_in_V_RID, "(port)m_axi_in_V_RID");
    sc_trace(mVcdFile, m_axi_in_V_RUSER, "(port)m_axi_in_V_RUSER");
    sc_trace(mVcdFile, m_axi_in_V_RRESP, "(port)m_axi_in_V_RRESP");
    sc_trace(mVcdFile, m_axi_in_V_BVALID, "(port)m_axi_in_V_BVALID");
    sc_trace(mVcdFile, m_axi_in_V_BREADY, "(port)m_axi_in_V_BREADY");
    sc_trace(mVcdFile, m_axi_in_V_BRESP, "(port)m_axi_in_V_BRESP");
    sc_trace(mVcdFile, m_axi_in_V_BID, "(port)m_axi_in_V_BID");
    sc_trace(mVcdFile, m_axi_in_V_BUSER, "(port)m_axi_in_V_BUSER");
    sc_trace(mVcdFile, in_V_offset, "(port)in_V_offset");
    sc_trace(mVcdFile, in_V_offset1, "(port)in_V_offset1");
    sc_trace(mVcdFile, out_V_V_TDATA, "(port)out_V_V_TDATA");
    sc_trace(mVcdFile, out_V_V_TVALID, "(port)out_V_V_TVALID");
    sc_trace(mVcdFile, out_V_V_TREADY, "(port)out_V_V_TREADY");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, in_V_blk_n_AR, "in_V_blk_n_AR");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, in_V_blk_n_R, "in_V_blk_n_R");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, icmp_ln140_reg_139, "icmp_ln140_reg_139");
    sc_trace(mVcdFile, out_V_V_TDATA_blk_n, "out_V_V_TDATA_blk_n");
    sc_trace(mVcdFile, i_0_reg_90, "i_0_reg_90");
    sc_trace(mVcdFile, in_V_addr_reg_133, "in_V_addr_reg_133");
    sc_trace(mVcdFile, icmp_ln140_fu_121_p2, "icmp_ln140_fu_121_p2");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage0_iter0, "ap_block_state9_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage0_iter1, "ap_block_state10_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state10_io, "ap_block_state10_io");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, i_fu_127_p2, "i_fu_127_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state9, "ap_condition_pp0_exit_iter0_state9");
    sc_trace(mVcdFile, add_ln142_fu_109_p2, "add_ln142_fu_109_p2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, zext_ln142_fu_105_p1, "zext_ln142_fu_105_p1");
    sc_trace(mVcdFile, in_V_offset_cast_fu_101_p1, "in_V_offset_cast_fu_101_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

StreamingDataflowPartition_0_IODMA_0_Mem2Stream::~StreamingDataflowPartition_0_IODMA_0_Mem2Stream() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state9.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state9.read()))) {
            ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state9.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln140_fu_121_p2.read()))) {
        i_0_reg_90 = i_fu_127_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        i_0_reg_90 = ap_const_lv10_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln140_reg_139 = icmp_ln140_fu_121_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        in_V_addr_reg_133 = add_ln142_fu_109_p2.read();
    }
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_add_ln142_fu_109_p2() {
    add_ln142_fu_109_p2 = (!zext_ln142_fu_105_p1.read().is_01() || !in_V_offset_cast_fu_101_p1.read().is_01())? sc_lv<64>(): (sc_biguint<64>(zext_ln142_fu_105_p1.read()) + sc_biguint<64>(in_V_offset_cast_fu_101_p1.read()));
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[8];
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[9];
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln140_reg_139.read()) && esl_seteq<1,1,1>(ap_const_logic_0, m_axi_in_V_RVALID.read()));
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln140_reg_139.read()) && 
   esl_seteq<1,1,1>(ap_const_logic_0, m_axi_in_V_RVALID.read())) || 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state10_io.read())));
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln140_reg_139.read()) && 
   esl_seteq<1,1,1>(ap_const_logic_0, m_axi_in_V_RVALID.read())) || 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state10_io.read())));
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_ap_block_state10_io() {
    ap_block_state10_io = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln140_reg_139.read()) && esl_seteq<1,1,1>(ap_const_logic_0, out_V_V_TREADY.read()));
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_ap_block_state10_pp0_stage0_iter1() {
    ap_block_state10_pp0_stage0_iter1 = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln140_reg_139.read()) && esl_seteq<1,1,1>(ap_const_logic_0, m_axi_in_V_RVALID.read()));
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_ap_block_state9_pp0_stage0_iter0() {
    ap_block_state9_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_ap_condition_pp0_exit_iter0_state9() {
    if (esl_seteq<1,1,1>(icmp_ln140_fu_121_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state9 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state9 = ap_const_logic_0;
    }
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_i_fu_127_p2() {
    i_fu_127_p2 = (!i_0_reg_90.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(i_0_reg_90.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_icmp_ln140_fu_121_p2() {
    icmp_ln140_fu_121_p2 = (!i_0_reg_90.read().is_01() || !ap_const_lv10_280.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_90.read() == ap_const_lv10_280);
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_in_V_blk_n_AR() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        in_V_blk_n_AR = m_axi_in_V_ARREADY.read();
    } else {
        in_V_blk_n_AR = ap_const_logic_1;
    }
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_in_V_blk_n_R() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln140_reg_139.read()))) {
        in_V_blk_n_R = m_axi_in_V_RVALID.read();
    } else {
        in_V_blk_n_R = ap_const_logic_1;
    }
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_in_V_offset_cast_fu_101_p1() {
    in_V_offset_cast_fu_101_p1 = esl_zext<64,63>(in_V_offset.read());
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_m_axi_in_V_ARADDR() {
    m_axi_in_V_ARADDR = in_V_addr_reg_133.read();
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_m_axi_in_V_ARBURST() {
    m_axi_in_V_ARBURST = ap_const_lv2_0;
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_m_axi_in_V_ARCACHE() {
    m_axi_in_V_ARCACHE = ap_const_lv4_0;
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_m_axi_in_V_ARID() {
    m_axi_in_V_ARID = ap_const_lv1_0;
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_m_axi_in_V_ARLEN() {
    m_axi_in_V_ARLEN = ap_const_lv32_280;
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_m_axi_in_V_ARLOCK() {
    m_axi_in_V_ARLOCK = ap_const_lv2_0;
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_m_axi_in_V_ARPROT() {
    m_axi_in_V_ARPROT = ap_const_lv3_0;
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_m_axi_in_V_ARQOS() {
    m_axi_in_V_ARQOS = ap_const_lv4_0;
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_m_axi_in_V_ARREGION() {
    m_axi_in_V_ARREGION = ap_const_lv4_0;
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_m_axi_in_V_ARSIZE() {
    m_axi_in_V_ARSIZE = ap_const_lv3_0;
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_m_axi_in_V_ARUSER() {
    m_axi_in_V_ARUSER = ap_const_lv1_0;
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_m_axi_in_V_ARVALID() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(m_axi_in_V_ARREADY.read(), ap_const_logic_1))) {
        m_axi_in_V_ARVALID = ap_const_logic_1;
    } else {
        m_axi_in_V_ARVALID = ap_const_logic_0;
    }
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_m_axi_in_V_AWADDR() {
    m_axi_in_V_AWADDR = ap_const_lv64_0;
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_m_axi_in_V_AWBURST() {
    m_axi_in_V_AWBURST = ap_const_lv2_0;
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_m_axi_in_V_AWCACHE() {
    m_axi_in_V_AWCACHE = ap_const_lv4_0;
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_m_axi_in_V_AWID() {
    m_axi_in_V_AWID = ap_const_lv1_0;
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_m_axi_in_V_AWLEN() {
    m_axi_in_V_AWLEN = ap_const_lv32_0;
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_m_axi_in_V_AWLOCK() {
    m_axi_in_V_AWLOCK = ap_const_lv2_0;
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_m_axi_in_V_AWPROT() {
    m_axi_in_V_AWPROT = ap_const_lv3_0;
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_m_axi_in_V_AWQOS() {
    m_axi_in_V_AWQOS = ap_const_lv4_0;
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_m_axi_in_V_AWREGION() {
    m_axi_in_V_AWREGION = ap_const_lv4_0;
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_m_axi_in_V_AWSIZE() {
    m_axi_in_V_AWSIZE = ap_const_lv3_0;
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_m_axi_in_V_AWUSER() {
    m_axi_in_V_AWUSER = ap_const_lv1_0;
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_m_axi_in_V_AWVALID() {
    m_axi_in_V_AWVALID = ap_const_logic_0;
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_m_axi_in_V_BREADY() {
    m_axi_in_V_BREADY = ap_const_logic_0;
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_m_axi_in_V_RREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln140_reg_139.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        m_axi_in_V_RREADY = ap_const_logic_1;
    } else {
        m_axi_in_V_RREADY = ap_const_logic_0;
    }
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_m_axi_in_V_WDATA() {
    m_axi_in_V_WDATA = ap_const_lv16_0;
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_m_axi_in_V_WID() {
    m_axi_in_V_WID = ap_const_lv1_0;
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_m_axi_in_V_WLAST() {
    m_axi_in_V_WLAST = ap_const_logic_0;
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_m_axi_in_V_WSTRB() {
    m_axi_in_V_WSTRB = ap_const_lv2_0;
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_m_axi_in_V_WUSER() {
    m_axi_in_V_WUSER = ap_const_lv1_0;
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_m_axi_in_V_WVALID() {
    m_axi_in_V_WVALID = ap_const_logic_0;
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_out_V_V_TDATA() {
    out_V_V_TDATA = m_axi_in_V_RDATA.read();
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_out_V_V_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln140_reg_139.read()))) {
        out_V_V_TDATA_blk_n = out_V_V_TREADY.read();
    } else {
        out_V_V_TDATA_blk_n = ap_const_logic_1;
    }
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_out_V_V_TVALID() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln140_reg_139.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        out_V_V_TVALID = ap_const_logic_1;
    } else {
        out_V_V_TVALID = ap_const_logic_0;
    }
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_zext_ln142_fu_105_p1() {
    zext_ln142_fu_105_p1 = esl_zext<64,32>(in_V_offset1.read());
}

void StreamingDataflowPartition_0_IODMA_0_Mem2Stream::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(m_axi_in_V_ARREADY.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            break;
        case 256 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln140_fu_121_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln140_fu_121_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXX";
            break;
    }
}

}

