// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _StreamingDataflowPartition_0_IODMA_0_Mem2Stream_16u_80u_s_HH_
#define _StreamingDataflowPartition_0_IODMA_0_Mem2Stream_16u_80u_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct StreamingDataflowPartition_0_IODMA_0_Mem2Stream_16u_80u_s : public sc_module {
    // Port declarations 56
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > m_axi_in_V_AWVALID;
    sc_in< sc_logic > m_axi_in_V_AWREADY;
    sc_out< sc_lv<64> > m_axi_in_V_AWADDR;
    sc_out< sc_lv<1> > m_axi_in_V_AWID;
    sc_out< sc_lv<32> > m_axi_in_V_AWLEN;
    sc_out< sc_lv<3> > m_axi_in_V_AWSIZE;
    sc_out< sc_lv<2> > m_axi_in_V_AWBURST;
    sc_out< sc_lv<2> > m_axi_in_V_AWLOCK;
    sc_out< sc_lv<4> > m_axi_in_V_AWCACHE;
    sc_out< sc_lv<3> > m_axi_in_V_AWPROT;
    sc_out< sc_lv<4> > m_axi_in_V_AWQOS;
    sc_out< sc_lv<4> > m_axi_in_V_AWREGION;
    sc_out< sc_lv<1> > m_axi_in_V_AWUSER;
    sc_out< sc_logic > m_axi_in_V_WVALID;
    sc_in< sc_logic > m_axi_in_V_WREADY;
    sc_out< sc_lv<16> > m_axi_in_V_WDATA;
    sc_out< sc_lv<2> > m_axi_in_V_WSTRB;
    sc_out< sc_logic > m_axi_in_V_WLAST;
    sc_out< sc_lv<1> > m_axi_in_V_WID;
    sc_out< sc_lv<1> > m_axi_in_V_WUSER;
    sc_out< sc_logic > m_axi_in_V_ARVALID;
    sc_in< sc_logic > m_axi_in_V_ARREADY;
    sc_out< sc_lv<64> > m_axi_in_V_ARADDR;
    sc_out< sc_lv<1> > m_axi_in_V_ARID;
    sc_out< sc_lv<32> > m_axi_in_V_ARLEN;
    sc_out< sc_lv<3> > m_axi_in_V_ARSIZE;
    sc_out< sc_lv<2> > m_axi_in_V_ARBURST;
    sc_out< sc_lv<2> > m_axi_in_V_ARLOCK;
    sc_out< sc_lv<4> > m_axi_in_V_ARCACHE;
    sc_out< sc_lv<3> > m_axi_in_V_ARPROT;
    sc_out< sc_lv<4> > m_axi_in_V_ARQOS;
    sc_out< sc_lv<4> > m_axi_in_V_ARREGION;
    sc_out< sc_lv<1> > m_axi_in_V_ARUSER;
    sc_in< sc_logic > m_axi_in_V_RVALID;
    sc_out< sc_logic > m_axi_in_V_RREADY;
    sc_in< sc_lv<16> > m_axi_in_V_RDATA;
    sc_in< sc_logic > m_axi_in_V_RLAST;
    sc_in< sc_lv<1> > m_axi_in_V_RID;
    sc_in< sc_lv<1> > m_axi_in_V_RUSER;
    sc_in< sc_lv<2> > m_axi_in_V_RRESP;
    sc_in< sc_logic > m_axi_in_V_BVALID;
    sc_out< sc_logic > m_axi_in_V_BREADY;
    sc_in< sc_lv<2> > m_axi_in_V_BRESP;
    sc_in< sc_lv<1> > m_axi_in_V_BID;
    sc_in< sc_lv<1> > m_axi_in_V_BUSER;
    sc_in< sc_lv<63> > in_V_offset;
    sc_in< sc_lv<32> > in_V_offset1;
    sc_out< sc_lv<16> > out_V_V_TDATA;
    sc_out< sc_logic > out_V_V_TVALID;
    sc_in< sc_logic > out_V_V_TREADY;


    // Module declarations
    StreamingDataflowPartition_0_IODMA_0_Mem2Stream_16u_80u_s(sc_module_name name);
    SC_HAS_PROCESS(StreamingDataflowPartition_0_IODMA_0_Mem2Stream_16u_80u_s);

    ~StreamingDataflowPartition_0_IODMA_0_Mem2Stream_16u_80u_s();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<10> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > in_V_blk_n_AR;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_logic > in_V_blk_n_R;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<1> > icmp_ln140_reg_139;
    sc_signal< sc_logic > out_V_V_TDATA_blk_n;
    sc_signal< sc_lv<6> > i_0_reg_90;
    sc_signal< sc_lv<64> > in_V_addr_reg_133;
    sc_signal< sc_lv<1> > icmp_ln140_fu_121_p2;
    sc_signal< bool > ap_block_state9_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state10_pp0_stage0_iter1;
    sc_signal< bool > ap_block_state10_io;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<6> > i_fu_127_p2;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_logic > ap_condition_pp0_exit_iter0_state9;
    sc_signal< sc_lv<64> > add_ln142_fu_109_p2;
    sc_signal< bool > ap_block_pp0_stage0_01001;
    sc_signal< sc_lv<64> > zext_ln142_fu_105_p1;
    sc_signal< sc_lv<64> > in_V_offset_cast_fu_101_p1;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_lv<10> > ap_NS_fsm;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<10> ap_ST_fsm_state1;
    static const sc_lv<10> ap_ST_fsm_state2;
    static const sc_lv<10> ap_ST_fsm_state3;
    static const sc_lv<10> ap_ST_fsm_state4;
    static const sc_lv<10> ap_ST_fsm_state5;
    static const sc_lv<10> ap_ST_fsm_state6;
    static const sc_lv<10> ap_ST_fsm_state7;
    static const sc_lv<10> ap_ST_fsm_state8;
    static const sc_lv<10> ap_ST_fsm_pp0_stage0;
    static const sc_lv<10> ap_ST_fsm_state11;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<16> ap_const_lv16_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_8;
    static const bool ap_const_boolean_0;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<6> ap_const_lv6_0;
    static const sc_lv<32> ap_const_lv32_28;
    static const sc_lv<6> ap_const_lv6_28;
    static const sc_lv<6> ap_const_lv6_1;
    static const sc_lv<32> ap_const_lv32_9;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_add_ln142_fu_109_p2();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state8();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_01001();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_state10_io();
    void thread_ap_block_state10_pp0_stage0_iter1();
    void thread_ap_block_state9_pp0_stage0_iter0();
    void thread_ap_condition_pp0_exit_iter0_state9();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_ready();
    void thread_i_fu_127_p2();
    void thread_icmp_ln140_fu_121_p2();
    void thread_in_V_blk_n_AR();
    void thread_in_V_blk_n_R();
    void thread_in_V_offset_cast_fu_101_p1();
    void thread_m_axi_in_V_ARADDR();
    void thread_m_axi_in_V_ARBURST();
    void thread_m_axi_in_V_ARCACHE();
    void thread_m_axi_in_V_ARID();
    void thread_m_axi_in_V_ARLEN();
    void thread_m_axi_in_V_ARLOCK();
    void thread_m_axi_in_V_ARPROT();
    void thread_m_axi_in_V_ARQOS();
    void thread_m_axi_in_V_ARREGION();
    void thread_m_axi_in_V_ARSIZE();
    void thread_m_axi_in_V_ARUSER();
    void thread_m_axi_in_V_ARVALID();
    void thread_m_axi_in_V_AWADDR();
    void thread_m_axi_in_V_AWBURST();
    void thread_m_axi_in_V_AWCACHE();
    void thread_m_axi_in_V_AWID();
    void thread_m_axi_in_V_AWLEN();
    void thread_m_axi_in_V_AWLOCK();
    void thread_m_axi_in_V_AWPROT();
    void thread_m_axi_in_V_AWQOS();
    void thread_m_axi_in_V_AWREGION();
    void thread_m_axi_in_V_AWSIZE();
    void thread_m_axi_in_V_AWUSER();
    void thread_m_axi_in_V_AWVALID();
    void thread_m_axi_in_V_BREADY();
    void thread_m_axi_in_V_RREADY();
    void thread_m_axi_in_V_WDATA();
    void thread_m_axi_in_V_WID();
    void thread_m_axi_in_V_WLAST();
    void thread_m_axi_in_V_WSTRB();
    void thread_m_axi_in_V_WUSER();
    void thread_m_axi_in_V_WVALID();
    void thread_out_V_V_TDATA();
    void thread_out_V_V_TDATA_blk_n();
    void thread_out_V_V_TVALID();
    void thread_zext_ln142_fu_105_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
